### ISSUE TITLE
External/OpenID authentication broken in latest

### ISSUE THREAD

**Issue by staticinvocation** [cortezaproject/corteza-server#107]
**Describe the bug**
External authentication does not work in the latest version of Corteza. Attempting to log in with an external provider produces the error `no provider for ... exists`.

**To Reproduce**

1. Provision Corteza with an external authentication provider
2. Try to sign in with it

**Expected behavior**
Be redirected to the external provider's authentication.

**Screenshots**

**Additional context**
This also occurs on the demo site, latest.cortezaproject.org

Seems to be broken some time between 2020.6 and 2019.12.

**Comment by darh** [comment]
Thanks @staticinvocation I'll take a look asap.
