### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by ghost** [cortezaproject/corteza-server#11]
Hello,

I would like to have the possibility to use PostgreSQL because my entire information system is only with PostgreSQL.

I'm looking to use OpenERP/Odoo/Tryton because they use PostgreSQL but in same time it's very time and money consuming to adapt them to be similar as Corteza.

Thank you

**Comment by darh** [comment]
Hey @colundrum! PostgreSQL (multi-db) support is planned in near future. Can not say antything about the timeline at the moment but there are some changes that need to be done (the db layer) and more thorough integration/e2e testing.

**Comment by fire** [comment]
I am still interested in this and cockroachdb as a replacement for postgresql.

**Comment by darh** [comment]
@fire if you have time & energy to tackle this, let me know

**Comment by fire** [comment]
Can you write a document or link me how the code is organized. Also mention how the db is accessed.

**Comment by darh** [comment]
should be quite clear if you inspect the code.

things to do:
 - refactor `repository` packages to allow multi-db support
 - migrate current db-layer to jmoiron/sqlx
 - add ability to configure which db to use
 
Integration tests have been implemented and cover most of the code that touches the db.

**Comment by fire** [comment]
Do you use triggers or sql function-likes?

**Comment by darh** [comment]
no.

**Comment by darh** [comment]
Implemented.
