### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by WizardKid** [cortezaproject/corteza-server#110]
Not sure if anyone viewing these issues. I am getting some errors while viewing for the first time in the browser. 
The Issue:
Could not read authentication system settings (//api.domain/system/auth/). Inspect your settings or contact your IT team.
Settings:
System API URL
//api.domain/system
Compose API URL
//api.domain/compose
Messaging API URL
//api.domain/messaging

Not sure what I did wrong but could someone point me to the right direction?

**Comment by darh** [comment]
@WizardKid  is Corteza API actually accessible (from your browser) on these URLs?

**Comment by WizardKid** [comment]
no they aren't

**Comment by WizardKid** [comment]
I am also getting this now
![Screenshot from 2020-09-11 16-44-36](https://user-images.githubusercontent.com/13104065/92946154-2abedf80-f44e-11ea-933c-fefd6c12138a.png)

**Comment by darh** [comment]
Should be. (ignore the unhealthy state for now please, healthcheck fix is on the way)

**Comment by WizardKid** [comment]
ok thank you

**Comment by WizardKid** [comment]
I can view the signup page but I am getting an "Error: failed to complete request due to internal error" when I signed up

**Comment by darh** [comment]
Best if you check container (server) logs.

**Comment by WizardKid** [comment]
Hi the errors I am getting in logs is:
![EA76AF13-D90C-49F5-B3B5-C0B48D74B350](https://user-images.githubusercontent.com/13104065/92957118-f48a5b80-f45f-11ea-9e40-1805270ef608.png)

**Comment by WizardKid** [comment]
for the past few days i have made a request for help on this and still haven't received help on this. I have deleted the server and tried again using the same guide from the documentations and no prevail.. the errors are the same and... silence

**Comment by WizardKid** [comment]
this is the latest error in logs `server_1   | {"level":"error","ts":1600605515.1863902,"logger":"corredor","caller":"corredor/service.go:427","msg":"could not load corredor server scripts","error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 172.20.0.2:80: connect: connection refused\"","stacktrace":"github.com/cortezaproject/corteza-server/pkg/corredor.(*service).loadServerScripts\n\t/drone/src/pkg/corredor/service.go:427"}`

**Comment by WizardKid** [comment]
receiving `Could not read authentication system settings (//api.apaxon.co.uk/system/auth/). Inspect your settings or contact your IT team.` on frontend  and api urls going to error 502 Bad Gateway

**Comment by WizardKid** [comment]
Update: managed to get to the login screen (as before, I have no idea because i just refreshed the browser as before). However, I am unable to create the first user and the error message is ` Error: failed to complete request due to internal error ` there is nothing in the logs to provide info on this internal error

**Comment by WizardKid** [comment]
could this be a jwt token error?

**Comment by WizardKid** [comment]
seems like I am speaking to myself on here.. However, I am updating this issue.. The user was created and I have received an email to confirmed my email etc.. however email can't be confirmed because of 
![Screenshot from 2020-09-20 15-49-28](https://user-images.githubusercontent.com/13104065/93714177-e7085c00-fb58-11ea-9e84-bcafdd09347b.png)
got this be a result of JWT and if so.. how do I generate one because that space is empty

**Comment by WizardKid** [comment]
Update: working perfectly fine

**Comment by AshlinR** [comment]
Hi, could you tell me how you resolved this issue as I am encountering the same issue but can't even get to logon form.
