### ISSUE TITLE
Error: could not extract store file: permission denied

### ISSUE THREAD

**Issue by ranjanmanish95** [cortezaproject/corteza-server#111]
Thanks for helping us to improve Corteza! We welcome all bug reports. Once we've verified and fixed your issue, we'll ping you in the comments to see if you can verify the fix.
We'll give you details on what version can be used to test the fix. Additionally, if you are interested in testing fixes that you ***didn't*** report, look for the issues with
the `status/to-test` label. You can pick any of these up for verification. ***You can delete this message portion of the bug report.***

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ranjanmanish95** [comment]
![Screenshot (405)](https://user-images.githubusercontent.com/33874102/93205357-50f9bd80-f775-11ea-8b43-bf8d4a5f6fe9.png)
1. corteza not uploading files or documents on the server.
2. Logs are showing Error: system.repository.Attachment.NotFound
3. Have hosted corteza server on EC2 instance using Docker-Compose. 
4. Also checked the permission on mysql(db) container on server and permissions are there.

**Comment by darh** [comment]
Hi @ranjanmanish95 

The attached screenshot shows error when you tried to access the unexisting attachment.
Are there any errors referring to failed upload?

Files are stored on the local (or remote) file system. I'm assuming you're using local FS here.
Can you share your docker-compose config?

**Comment by darh** [comment]
@ranjanmanish95 can you share how you solved this?

**Comment by ranjanmanish95** [comment]
hi darh,
1. I m trying to upload the file in corteza but it is not getting uploaded and logs r showing error. Also i tried to upload logo but it is showing same error in logs.
2. Files are stored in remote file system i believe since it is hosted in on EC2 instance.
Attaching screenshots:
![Screenshot (410)](https://user-images.githubusercontent.com/33874102/93214107-61646500-f782-11ea-88ae-7b3d0b41edc1.png)
![Screenshot (411)](https://user-images.githubusercontent.com/33874102/93214114-645f5580-f782-11ea-9302-26ac411fa6f5.png)

**Comment by ranjanmanish95** [comment]
> @ranjanmanish95 can you share how you solved this?

sorry by mistake i closed it.

**Comment by ranjanmanish95** [comment]
> Hi @ranjanmanish95
> 
> The attached screenshot shows error when you tried to access the unexisting attachment.

> Are there any errors referring to failed upload?

hi denis, 
When i tried to upload files it was not uploaded and when i tried to check the logs it was showing this error. Also i tried to upload file on my local and it worked.

**Comment by ranjanmanish95** [comment]
Error: system.repository.AttatchmentNotFound changed to Error: could not extract store file: permission denied
@denis sorry i dont know why logs were showing incorrect. The error is this one: could not extract store file: permission denied.
![Screenshot (413)](https://user-images.githubusercontent.com/33874102/93293568-dcbb2a80-f805-11ea-8404-cefa4a8f2038.png)

**Comment by darh** [comment]
Can you double check these things for me:
a) Does uploaded file actually exists on the disk?
b) ownership and permission bits for the file

**Comment by ranjanmanish95** [comment]
> Can you double check these things for me:
> a) Does uploaded file actually exists on the disk?
> b) ownership and permission bits for the file

I dont know where to check the uploaded file. I have checked the corteza database. There also no clue of anything.
Attaching all the screenshots of ownership and permission bits :
![Screenshot (414)](https://user-images.githubusercontent.com/33874102/93314628-a8f0fc80-f827-11ea-9566-56cfb035672f.png)
![Screenshot (415)](https://user-images.githubusercontent.com/33874102/93314635-aabac000-f827-11ea-93c9-f9eeef256a04.png)
![Screenshot (416)](https://user-images.githubusercontent.com/33874102/93314638-ab535680-f827-11ea-860a-596bce88aafb.png)

**Comment by ranjanmanish95** [comment]
hi denis,
I have solved the issue. Acutally write permission was not there in my _data directory which is the source path of my docker volume where my data was getting stored. 
Thanks.
