### ISSUE TITLE
Inline editing for record lists - not working

### ISSUE THREAD

**Issue by venkteshm** [cortezaproject/corteza-server#123]
Inline editing for record lists is not working. I tried it on the demo instance at https://demo.crust.tech/. On the page builder for the record list, the checkbox next to block.recordList.record.editable is checked, and couple of fields have been selected under Editable module fields.

**Comment by lennyhorstink** [comment]
Hi @venkteshm. Can you point me to the exact place where you have the issue. When I edit a pricebook in the CRM namespace (direct link: https://demo.crust.tech/compose/ns/crm/pages/152397302781181956/record/169115839730024452) I can use the inline editor correctly.

**Comment by darh** [comment]
I'm closing this. If it's still an issue, reopen it.
