### ISSUE TITLE
Question: Can this be used for Citizen services, e.g complaints logging,  case handling? 

### ISSUE THREAD

**Issue by anborg** [cortezaproject/corteza-server#138]
Hi Corteza, 

Thank you for this great tool. 

I searched around, and saw this CRM. The description says "Sales". Can Corteza be used for tracking "complaints" Cases for local **_government citizen requests/complaints_**?

The organization only allows **windows without Docker supportable hardware!** Please let me know how I can build exe for windows, and to add db config to a config.yml

Thank you

**Comment by lennyhorstink** [comment]
Hi Anborg,

Yes, it would be possible to create that. The CRM is built on top of the Corteza Low-Code Platform, so it's just one of the apps you could use / customize / build. There is good info in the documentation on docs.cortezaproject.org.

Feel free to reach out to me at lenny.horstink@crust.tech :)

**Comment by anborg** [comment]
Thanks @lennyhorstink ,

>how I can build exe for windows, and to add db config to a config.yml

I did read the full docs.  But _could not find any instruction on building an exe_ for windows. Would be great if we could have that documented somewhere -- that way non-docker environments can build and experiment.

How do I compile these to windows exe, and run, without docker?
![image](https://user-images.githubusercontent.com/56970398/108108304-78272480-705e-11eb-8126-5d484258314e.png)

**Comment by darh** [comment]
That's not supported at the moment. 
Building go-lang app is not much different on windows; please inspect the Makefile, drone.yaml and see how it's done for Linux.

If you manage to build it and document it, we'll be happy to extend our documentation

**Comment by anborg** [comment]
Hi @darh 

Do I need to change sqlite version to get rid of this error? I'm not good with c.

```sh
C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server>make build
GOOS=windows GOARCH=amd64 go build -ldflags "-X github.com/cortezaproject/corteza-server/pkg/version.Version=2020.12.2 " -o build/corteza-server-2020.12.2-windows-amd64.exe cmd/corteza/main.go
# github.com/cortezaproject/corteza-server/system/commands
system\commands\users.go:112:45: cannot use syscall.Stdin (type syscall.Handle) as type int in argument to terminal.ReadPassword
system\commands\users.go:156:44: cannot use syscall.Stdin (type syscall.Handle) as type int in argument to terminal.ReadPassword
make: *** [Makefile:77: build/corteza-server-2020.12.2-windows-amd64.exe] Error 2
```

**Comment by anborg** [comment]
Ok, I casted those error lines to **int()** . I was able to generate the binaries. 
```go
cmd.Print("Set password: ")
if password, err = terminal.ReadPassword(int(syscall.Stdin)); err != nil {
  cli.HandleError(err)
}
```

```
C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server>build\corteza-server-2020.12.2-windows-amd64.exe serve-api
...

{"level":"error","ts":1613785664.687832,"logger":"corredor","caller":"corredor/service.go:889","msg":"could not load corredor client scripts","error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection closed","stacktrace":"github.com/cortezaproject/corteza-server/pkg/corredor.(*service).loadClientScripts\n\tC:/data/projects/projects_go/src/github.com/cortezaproject/corteza-server/pkg/corredor/service.go:889"}
{"level":"info","ts":1613785666.6461456,"logger":"http","caller":"server/server.go:102","msg":"HTTP server stopped"}

```

Looking to see, where add corridor config ...

**Comment by darh** [comment]
\cc @formaldehid ^

**Comment by darh** [comment]
Is this still an issue?
