### ISSUE TITLE
session-store-secret leaks into logs 

### ISSUE THREAD

**Issue by adamdecaf** [cortezaproject/corteza-server#14]
This project looks fantastic and useful for an internal dashboard of several applications and teams. Thanks in advance as we're looking to build off of Corteza! 

**Describe the bug**
Some log lines contain sensitive information like:

```
system_1     | {"level":"info","ts":1566502103.9435697,"logger":"system.service.settings.discovery","caller":"service/settings_autodiscovery.go:93","msg":"value auto-discovered","name":"auth.external.session-store-secret","type":"string","default":"Brrtelyakaqtx8pGF4ONcCD5r4BdrTP4s5ct2gK8hCXsa2WGNCSlmSHc6eRJ1jB7"}
```

**To Reproduce**
Run the system docker image (`cortezaproject/corteza-server-system:latest`)

**Expected behavior**
Sensitive bits are masked so as to not appear in logs. I notice this is done elsewhere already.

**Comment by darh** [comment]
Hi @adamdecaf 
Thank you. Wil fix.
