### ISSUE TITLE
Could not load record list: pq. invalid value ".4" for "HH24"

### ISSUE THREAD

**Issue by Carl4** [cortezaproject/corteza-server#142]
## Describe the bug

Postgres date ordering causes results in errors. somehow the escaped quotes are making it through to the query that's passed to postgres.

## To Reproduce

1. Run the 2020.12.2 docker image with a Postgres (v. 11.11).
2. Enter some tasks.
3. View the task list page

## Expected behavior
Tasks display and sort properly.

## Screenshots

Note: I tweaked my CRM Tasks List so it didn't use dates and now it doesn't produce the error any more.  So here's a screen shot from a Case. 

`Could not load record list: pq. invalid value ".4" for "HH24"`

![image](https://user-images.githubusercontent.com/1817460/109057884-4f330f00-76b0-11eb-8228-49b75ae531fb.png)

**Additional context**

Looks like this comes from the date formatting string here: 

https://github.com/cortezaproject/corteza-server/blob/e6bdf69defe337a8a0ca09a07c6e19d8e2c15722/store/postgres/sql_typecasters.go#L30

Somehow the quotes and the escape characters are being passed through to the underlying postgresql and then interpreted as characters.  Because of the string \"T\", this causes the parser to skip 4 extra characters.  As a result, the parser tries to read ".x" as an hour because that comes several characters after HH24 was supposed to match.

The quotes look correct to me -- like they're escaped only from the go compiler.  I wonder if this isn't the result of being passed through an escape function after the string is generated?

**Comment by darh** [comment]
Thank you for the bug summary @Carl4 
We'll try to address it and close it before next release.

**Comment by petergrlica** [comment]
Hi @Carl4, thanks for the report.

This issue was already fixed in 2020.12.x and will be included in the 2020.12.3 patch.
If you want to check, the fix was commited at https://github.com/cortezaproject/corteza-server/commit/e6bdf69defe337a8a0ca09a07c6e19d8e2c15722

**Comment by darh** [comment]
Deployed.
