### ISSUE TITLE
Question: Does rest or gRPC api have an option to create a Case, Contact?

### ISSUE THREAD

**Issue by anborg** [cortezaproject/corteza-server#144]
Q: Does rest-api have an option to create a Case, Contact?

![image](https://user-images.githubusercontent.com/56970398/110188633-6b3e5b00-7dea-11eb-8a8a-55bb34364edc.png)

![image](https://user-images.githubusercontent.com/56970398/110188736-c2443000-7dea-11eb-9259-d38fb89e1d74.png)

**Comment by darh** [comment]
Sure

Please see the docs:
https://docs.cortezaproject.org/corteza-docs/2020.12/examples/compose-api/index.html#_creating_a_record

You can find REST API docs where you're serving your API, something liek
https://..../api/docs or https://..../docs

**Comment by anborg** [comment]
Thanks @darh ,

Looks like I need to learn about different concepts in End User Guide  to better understand attributes of Case and its related objects. And perhaps later come to Integrator Guide ... And later to compose api ...

Side question: Is gRPC port also exposed for CRUD operations on Case/Contact objects? That may be easier as it is more typed , and I can try generating clients with proto.

Thanks again.

**Comment by tjerman** [comment]
@darh correct me if I'm wrong, but gRPC is used for internal system comms and is not accessible from the outside

**Comment by darh** [comment]
Correct -- gRPC is internal only. Missed that part of the question.

**Comment by anborg** [comment]
thank you. I find the tool very interesting. Will revisit to learn more - specifically about integration with other systems, so I can be an ambassador :).

**Comment by darh** [comment]
Great! Enjoy
