### ISSUE TITLE
The generated tar files with a "make release" command are not working?

### ISSUE THREAD

**Issue by AsadShoaib111** [cortezaproject/corteza-server#147]
After cloning a corteza-server repository, I can generate tar files with "make release" command but those tar files are not working whereas tar files downloaded from https://releases.cortezaproject.org/files/ are working. I would really appreciate it if someone would let me know how to generate a working tar files from corteza-server. It might have to do something with the build process, kindly help me out. thanks.

**Comment by darh** [comment]
Leaving this here for anyone who's interested:

- check Makefile and .drone-ci.yml on server to see how binaries are produced
 - check corteza-docker repository and Dockerfiles + accompanying scripts to see how .tar files are pulled in
 - there is no need for you to create tar files; we do this step because we need build pipeline broken 

@AsadShoaib111 can you elaborate a bit what "not working" means?

**Comment by AsadShoaib111** [comment]
hi, thanks for responding, 

Yes I have checked Makefile and .drone-ci.yaml. 

I did able to run the server on my local machine by make codegen and make watch.

The build binary seems to work locally but when I create a docker image from the corteza-server build binary, I do receive "exec user process caused "exec format error". while deploying containers from those docker images.

can you please share the step by step process for making a working build, thanks.

**Comment by darh** [comment]
You have to be sure that binary format (target os, arch) matches.
So, if you compile on mac/win without explicitly saying that you're compiling for linux/amd64 you'll get the error you're getting.

See BUILD_* variables in makefile:

**Comment by AsadShoaib111** [comment]
hi darh, I did assigned BUILD_OS to linux but I was receiving some sql lite related errors and build was failing, can you please let me know any work around, thanks.

**Comment by anborg** [comment]
cast to int as mentioned here, you could get past that error.

https://github.com/cortezaproject/corteza-server/issues/138#issuecomment-782510222

**Comment by darh** [comment]
Inactive, closing.
