### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by reidlai** [cortezaproject/corteza-server#148]
Dear All,

As I know, Corteza server can serve as REST or gPRC server.  And Low Code can allow us to create customized namespace for different application.  It is great.

If I am now going to create name space say eCommerce or Customer Loyalty, these applications are facing public users.  Should these public users must have a Corteza user account? If so, can they call self-service API to register user account, forget password, etc?  

Thanks for your advice.

**Comment by darh** [comment]
@reidlai 

Corteza currently supports only REST. gRPC is used for some internal, cross-service comm.

If "call self-service API" means call API endpoints to create accounts, init forgot password flow etc - then yes.

Please note that with 2021.3 release (will be available by end of this month), we're introducing some improvements reg. auth flows. We'll support OAuth2 flows and corteza server will internally have authentication screens for the users (registration, login, forgotten password, profile, oauth2 client authorization, session management).

**Comment by reidlai** [comment]
@darh Thanks a lot.  Will try it by my own.

**Comment by reidlai** [comment]
Is there any way to access login api endpoint $SystemAPI/auth/internal/login using REST API? In my location configuration, I change API based URL to /api, so I call login endpoint as follow:

curl -v -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{"email": "xxx@gmail.com", "password": "********"}' http://localhost:18080/api/system/auth/internal/login

where xxx@gmail.com and ***** password are valid credential in web app ... i am now using version 2021.3.  Is there any official example to demonstrate how to use REST api to login?
