### ISSUE TITLE
Seperate Single Write (Event) Store and at least single Read (Data) Store

### ISSUE THREAD

**Issue by reidlai** [cortezaproject/corteza-server#149]
Based on CQRS/ES concept, we should separate single Store into Write Store and Read Store.  For some scenario, I also recommend to support multiple Read Store when remote database query is required.   Multiple Read store applies to mBaaS which connect to back-end data store for dashboard preparation.

**Comment by darh** [comment]
Can you elaborate this a bit? How do you see this implemented?

**Comment by reidlai** [comment]
According to CQRS pattern, we need to implement command and query.  Command will dispatch event to event store (write store) and projector will consolidate all immutable event data into latest state and update in data store (read store).  Query will directly connect to data store or through middle-ware for inquiry.

Under enterprise environment, we usually separate these two data store for recovery, just like traditional write-ahead log before updating traditional database.

**Comment by reidlai** [comment]
I know Corteza has implemented actionlog and store same as CQRS pattern.   But is it possible that we use multiple DSN (database) for data persistence, say using Redis/TiKV as eventstore/actionlog?

**Comment by darh** [comment]
Corteza does not implement CQRS. 
Actionlog entries can not be used as commands but it serves more as some kind of an audit log.

Multi-db support will come shortly.

**Comment by reidlai** [comment]
sorry, coz may be confused with eventbus with CQRS terms.   Will close this issue.  Thanks

**Comment by reidlai** [comment]
Closed
