### ISSUE TITLE
sonyflake causing crash on startup 

### ISSUE THREAD

**Issue by mingfang** [cortezaproject/corteza-server#15]
`docker run -e DB_DSN="corteza:change-me@(250.2.89.8:3306)/corteza" cortezaproject/corteza-server-system `

{"level":"info","ts":1566740547.1042073,"logger":"system.database","caller":"db/connector.go:77","msg":"connected to the database","name":"system","dsn":"c****a:c****e@(250.2.89.8:3306)/corteza"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x84f4b7]

goroutine 1 [running]:
github.com/cortezaproject/corteza-server/vendor/github.com/sony/sonyflake.(*Sonyflake).NextID(0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cortezaproject/corteza-server/vendor/github.com/sony/sonyflake/sonyflake.go:89 +0x37
github.com/cortezaproject/corteza-server/vendor/github.com/titpetric/factory.(*SonyflakeFactory).NextID(...)
	/go/src/github.com/cortezaproject/corteza-server/vendor/github.com/titpetric/factory/sonyflake.go:31
github.com/cortezaproject/corteza-server/system/internal/repository.(*application).Create(0xc0001d7520, 0xc000187320, 0x20, 0xb60780, 0x20)
	/go/src/github.com/cortezaproject/corteza-server/system/internal/repository/application.go:71 +0x35
github.com/cortezaproject/corteza-server/system.makeDefaultApplications.func1(0xc000187320, 0xc45a40, 0x13cf201)
	/go/src/github.com/cortezaproject/corteza-server/system/autosetup.go:68 +0x12a
github.com/cortezaproject/corteza-server/system/types.ApplicationSet.Walk(0xc00014b830, 0x1, 0x1, 0xc00014b848, 0x0, 0x0)
	/go/src/github.com/cortezaproject/corteza-server/system/types/application.gen.go:18 +0x60
github.com/cortezaproject/corteza-server/system.makeDefaultApplications(0xdb8f80, 0xc00018c030, 0xc00020c000, 0xc000001680, 0x0, 0x0)
	/go/src/github.com/cortezaproject/corteza-server/system/autosetup.go:60 +0x34c
github.com/cortezaproject/corteza-server/system.Configure.func3(0xdb8f80, 0xc00018c030, 0xc00020c000, 0xc000001680, 0xc000188390, 0xc13ce0)
	/go/src/github.com/cortezaproject/corteza-server/system/system.go:60 +0x67a
github.com/cortezaproject/corteza-server/pkg/cli.Runners.Run(0xc00000e638, 0x1, 0x1, 0xdb8f80, 0xc00018c030, 0xc00020c000, 0xc000001680, 0xc00014bcc8, 0x8)
	/go/src/github.com/cortezaproject/corteza-server/pkg/cli/runner.go:116 +0x7f
github.com/cortezaproject/corteza-server/pkg/cli.(*Config).MakeCLI.func2(0xdb8f80, 0xc00018c030, 0x0, 0x0)
	/go/src/github.com/cortezaproject/corteza-server/pkg/cli/runner.go:262 +0xaa
github.com/cortezaproject/corteza-server/pkg/api.(*Server).Command.func1(0xc00020c280, 0x13cf218, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cortezaproject/corteza-server/pkg/api/server.go:65 +0x1bb
github.com/cortezaproject/corteza-server/vendor/github.com/spf13/cobra.(*Command).execute(0xc00020c280, 0xc00000c090, 0x0, 0x0, 0xc00020c280, 0xc00000c090)
	/go/src/github.com/cortezaproject/corteza-server/vendor/github.com/spf13/cobra/command.go:751 +0x519
github.com/cortezaproject/corteza-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00020c000, 0xdb8f80, 0xc00018c030, 0xc00020c000)
	/go/src/github.com/cortezaproject/corteza-server/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/cortezaproject/corteza-server/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cortezaproject/corteza-server/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/go/src/github.com/cortezaproject/corteza-server/cmd/system/main.go:11 +0x9e

**Comment by mingfang** [comment]
It looks like sonyflake does not like the Docker container network interface.
Changing to the host network works
`docker run -e DB_DSN="corteza:change-me@(250.2.89.8:3306)/corteza" --net=host cortezaproject/corteza-server-system`

**Comment by mingfang** [comment]
I think the problem is here https://github.com/sony/sonyflake/blob/4ae3f1aeaadd860acf428bc6ad1cba01d7b6bfd4/sonyflake.go#L155

My Docker/Kubernetes network CIDR is 250.0.0.0/8 and this code doesn't like that.
My host network is 192.168.1.0/24 and therefore that works.

I don't know it checks that.  Sonyflake looks very old and abandoned.  Maybe there is an alternative.

**Comment by titpetric** [comment]
The network address you’re using is not a valid LAN space address (IANA
defines 244-255/8 as reserved space, which shouldn’t be used). Do you have
a particular reason for this?

I’ll add in support for setting the sonyflake server ID manually or from a
single IP address (regardless if in a LAN). Please don’t consider this a
fix for your particular issue, you should definitely follow IANA and use a
network class intended for local networks(10.0.0.0/8 for example, or a
smaller allocation). The improvement made will be for supporting DMZ only
deployments without a LAN address.

**Comment by mingfang** [comment]
+1 for adding ability to manually set the sonyflake id.
I have my reasons for using this CIDR.

**Comment by gil0109** [comment]
@titpetric I am on openshift and getting this error.  How do I set a particular address?

**Comment by darh** [comment]
Looks like this needs to be properly addressed.
https://forum.cortezaproject.org/t/install-on-openshift-fail-with-invalid-memory-address/1140/3

**Comment by darh** [comment]
Will be part of 2022.9.3 patch release
