### ISSUE TITLE
Allow Tabs to be applications

### ISSUE THREAD

**Issue by zayn008** [cortezaproject/corteza-server#158]
For example the case tab should have a shortcut in the applications menu and have the options to be isolated or behave as a ‘child’ application, e.g like an app but using the parents database

**Comment by darh** [comment]
@zayn008 not sure if I understand this proposal. Maybe you're just using a different terminology here.

Care to elaborate a bit or provide an example?

**Comment by zayn008** [comment]
@darh Sure, so I suppose we could call it federated apps. E.g Apps that use a parent app for data. Take Service Solution, we should be able to have this behave as a child app of CRM, inheriting data from it e.g sales, accounts, products.

Ignore the 'tabs' bit, it should be focused on having Child and Parent applications. E.g If I wanted to take the Products section of the CRM and have a more focused space to work in. While the tab in CRM would act as a parent/summary page. Or If I wanted to do the above Service solution in reverse, I would take Cases, create a child application of the CRM and have a more focused Case section like the Service Solution

**Comment by darh** [comment]
Ok, I understand now. I would like to avoid "federated" term as it's (ab)used in other places :)
There are internal talks about remaking Compose in the similar way you described.

\cc @zmija see prev. comment, interesting perspective.

**Comment by darh** [comment]
Obsolete. Tabs in corteza-one are now deprecated.
