### ISSUE TITLE
error: could not load requested bundle

### ISSUE THREAD

**Issue by ranjanmanish95** [cortezaproject/corteza-server#159]
**describe the bug**
@darh @tjerman I have uploaded my extension onto the corredor container and deployed but the corredor logs are showing me error: could not load requested bundle.
![Screenshot (43)](https://user-images.githubusercontent.com/33874102/113134386-58c70e00-923e-11eb-98f6-bec3a9d2b6b2.png)
 version is 2020.6.

**To Reproduce**
1. Defined my own extension. Folder Structure is like this:-
    ./corredor/test-extension/client-scripts/compose/crm/Lead/setDistrictDropdown.js.
   I have used the prefill templates as i was trying to prefill the district dropdown using my values. (static or dyanmic)

**Expected behavior**
 Upon clicking on the Lead module record page add button it should prefill the district dropdown with my own values but its not giving any response. Also i checked live server logs but it is not logging any update.

**Screenshots**
I am attaching here corredor and server logs screenshots.
![Screenshot (43)](https://user-images.githubusercontent.com/33874102/113137379-169fcb80-9242-11eb-877a-f2220ca51aa4.png)
![Screenshot (44)](https://user-images.githubusercontent.com/33874102/113137898-bf4e2b00-9242-11eb-8419-563aaf529ebd.png)

**Additional context**
Also, I am pretty confused about bundling of client scripts as it is mentioned in the document. We have to upload the bundled script inside each application folder like compose or just need to add the webpack dependency in package.json file.
Please help me on this.*

**Comment by darh** [comment]
Is this still an issue?
