### ISSUE TITLE
msg":"could not load corredor server scripts","error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 172.23.0.2:80: connect: connection refused

### ISSUE THREAD

**Issue by ranjanmanish95** [cortezaproject/corteza-server#161]
@darh

**{"level":"error","ts":1617686346.9232132,"logger":"corredor","caller":"corredor/service.go:850","msg":"could not load corredor client scripts","error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 172.23.0.2:80: connect: connection refused\"","stacktrace":"github.com/cortezaproject/corteza-server/pkg/corredor.(*service).loadClientScripts\n\t/drone/src/pkg/corredor/service.go:850"}**

 
I am getting this error while checking my server container logs. Corteza version is 2020.6.
Although i checked the troubleshooting documentation of 2021.3 but its written to check the changes made to the configuration if problem still persists.
I dont know what changes we need to track. Please throw some light on this.
![Screenshot (63)](https://user-images.githubusercontent.com/33874102/113675930-81855280-96d9-11eb-9136-9b684ab665c0.png)

**Comment by darh** [comment]
Are you running Corredor server and is configuration ok (server ip, port...)
If you're not running it, you can always use `CORREDOR_ENABLED=false`

**Comment by ranjanmanish95** [comment]
@darh yeah i m running Corredor server and configuration is ok it seems. Just few days ago it was working fine. I need corredor server because i want to integrate my own extension with my automation scripts.
Also the version i m using is 2020.6. So is it the version issue because there is no repo available of that version on github??
Also please guide me on bundling of client scripts and debugging of scripts in general.

**Comment by darh** [comment]
If it worked a few days ago, what changed?
Did you restart something? Is there anything useful in corredor container logs?

If you do not have a good reason to run 2020.6 I urge you to upgrade to at least 2020.9 if not 2020.12.

**Comment by ranjanmanish95** [comment]
@darh ok denis i will upgrade it. Thanks a lot for the help. Also i m currently moving on to 2020.12 version but i will upgrade to  2021.3 version once it is stable.

**Comment by darh** [comment]
Closing this.

**Comment by ranjanmanish95** [comment]
kk np.
