### ISSUE TITLE
Not all applications visible in new tab (ver 2021.3)

### ISSUE THREAD

**Issue by micebrain** [cortezaproject/corteza-server#164]
In the new release, the viewport for Applications list "disappeared" or "cut off" from the display. There is no scrollbar to indicate that there are more applications. For small screen it looks like some applications disappeared. Switching to fullscreen I found that it is simply cut off by the view size.

<img width="1092" alt="Screenshot 2021-04-08 at 19 02 53" src="https://user-images.githubusercontent.com/7136209/114068816-98c16d00-989e-11eb-95ee-60e9b61e00ac.png">

**Comment by zmija** [comment]
hi @micebrain,

Thanks for reporting this. I fixed it a few hours ago (https://github.com/cortezaproject/corteza-webapp-one/commit/7876a0601cb6aaedacf015716b4d0fc4372734a0) and we'll probably release a new version early next week.

Cheers
