### ISSUE TITLE
Unable to run application in https (ver 2021.3)

### ISSUE THREAD

**Issue by micebrain** [cortezaproject/corteza-server#165]
I deploy the application in docker container with a reverse proxy setup to route the traffic to the container. 
I am able to login however the redirect with the token code is not working as the browser disallowed mixed content 
<img width="1266" alt="Screenshot 2021-04-10 at 18 54 13" src="https://user-images.githubusercontent.com/7136209/114278332-9cd0c480-9a2f-11eb-90f1-19536db88fa3.png">

**Comment by akshaykumararavindan** [comment]
I was able to get rid of that error by setting the AUTH_BASE_URL='https://mydomain.tld', but once I did that the app is stuck in an infinite redirect loop. @darh would you be able to shed some light on this?

**Comment by darh** [comment]
Try with `AUTH_BASE_URL='https://mydomain.tld/auth'`

**Comment by akshaykumararavindan** [comment]
Thanks @darh. It resolved the issue. Do you want this to be documented? Or will there be a change in the next release?

**Comment by darh** [comment]
Should be documented with AUTH_BASE_URL var (see `pkg/options/auth.yaml`).

However, if you see how the default logic for this var works you can see that it tries to guess hostname and ssl/no-ssl from a couple of other settings (see `pkg/options/helpers.go`). I've made some brave assumptions about environment and presence of variables `DOMAIN`,
`VIRTUAL_HOST`, `LETSENCRYPT_HOST`, ... that turned out wrong.

So, for one of (near) future releases, we'll make this auto-configuration logic more helpful, and informative.
Also, expect some kind of self-diagnostic tools or panels so you could help to figure out what is wrong...

**Comment by PaulMcF1987** [comment]
@darh I have a similar issue in that when I try to access corteza, it gets stuck in a loading loop (https://forum.cortezaproject.org/t/upgraded-to-2021-3-but-cannot-access-corteza/75/5)

Based on your last comment, would I be right to assume that this may be something to do with the fact that I have used a LetsEncrypt SSL?

I am hoping that this fix will work for me, I have tried adding the `AUTH_BASE_URL='https://mydomain.tld/auth'` to different areas in the .env and .YAML files but no joy.

Can I check where it is supposed to be added?



------------------------------------------------------------------------------------------------------------------------------------------
I tried adding to .env

# Database connection
DB_DSN=user:pswd@tcp(db:3306)/dbname?collation=utf8mb4_general_ci
AUTH_JWT_SECRET=secret_key
AUTH_BASE_URL=‘https://mydomain.tld/auth’
LOG_LEVEL=info

No joy though. Is there somewhere else that this is supposed to go?

**Comment by PaulMcF1987** [comment]
@darh I notice when I inspect the page and look at the consol tab
I get a flash between an empty screen and a blue band at the top that has the corteza details `Corteza One, version:bf86af3, build time: 2021-04-06:T08:10:57.7637`

If I view sources, the top 3 items remain consistent:
`mycorteza.mydomain.tld  >>  api-mycorteza.mydomain.tld/auth/oauth2  >>  default-client?redirect_uri=https://corteza.eazyfreight.co.uk/auth/callback&scope=profile api`

There are then some folders flashing up and disappearing below:
CSS
JS
config.js
Webpack://

On the network tab I get a similar story

It appears to me that the install is fine but that there may be something blocking
I have added `AUTH_BASE_URL=‘https://mydomain.tld/auth’` as mentioned above but no joy

**Comment by darh** [comment]
Make sure that domain in AUTH_BASE_URL actually matches your domain and that there is HTTPS in you use HTTPS!

Second thing you can check:

If you go to your db and see contents of auth_clients table. Set value on the redirect_uris column to an empty string (might just well be on all clients for now if you have more than one).

**Comment by micebrain** [comment]
> Should be documented with AUTH_BASE_URL var (see `pkg/options/auth.yaml`).
> 
> However, if you see how the default logic for this var works you can see that it tries to guess hostname and ssl/no-ssl from a couple of other settings (see `pkg/options/helpers.go`). I've made some brave assumptions about environment and presence of variables `DOMAIN`,
> `VIRTUAL_HOST`, `LETSENCRYPT_HOST`, ... that turned out wrong.
> 
> So, for one of (near) future releases, we'll make this auto-configuration logic more helpful, and informative.
> Also, expect some kind of self-diagnostic tools or panels so you could help to figure out what is wrong...

Thanks, setting AUTH_BASE_URL helps. Unfortunately this variable is not documented - `pkg/options/auth.yaml` only defined the env vars AUTH_JWT_SECRET and AUTH_JWT_EXPIRY

**Comment by darh** [comment]
Are you sure you're looking at the right branch?
https://github.com/cortezaproject/corteza-server/blob/2021.3.x/pkg/options/auth.yaml

**Comment by micebrain** [comment]
@darh Yes, the branch 2021.3.x
The closest to that I can see based on the link looks like this

```
  - name: baseURL
    default: guessBaseURL() + "/auth"
    description: |-
      Frontend base URL. Must be an absolute URL
```
And from the documentation on the site:
https://docs.cortezaproject.org/corteza-docs/2021.3/devops-guide/configuration/server.html#_authentication

**Comment by darh** [comment]
Oh, nice catch. Thank you @micebrain 

@tjerman looks like we need to regenerate options docs for .3 release.

**Comment by darh** [comment]
This was fixed.
