### ISSUE TITLE
REST Internal Login API

### ISSUE THREAD

**Issue by reidlai** [cortezaproject/corteza-server#167]
Is there any way to access login api endpoint $SystemAPI/auth/internal/login using REST API? In my location configuration, I change API based URL to /api, so I call login endpoint as follow:

curl -v -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{"email": "xxx@gmail.com", "password": "********"}' http://localhost:18080/api/system/auth/internal/login

where xxx@gmail.com and ***** password are valid credential in web app ... i am now using version 2021.3. Is there any official example to demonstrate how to use REST api to login?

**Comment by darh** [comment]
WIth v2021.3  we removed most of `system/auth/*` endpoints, mainly because we migrated fully to to OAuth2 flow.
There is no way to authenticate users like in your example. They have to authenticate themselves against auth server (part of Corteza server).

**Comment by reidlai** [comment]
is there document to document the flow?  thanks for your info

**Comment by darh** [comment]
Documentation on where the specific endpoints are is still missing. However -- this is standard OAuth2 flow.

Endpoints are here:
`.../auth/oauth2/authorize`
`.../auth/oauth2/token`
