### ISSUE TITLE
Error: failed to complete request due to internal error (version=2020.9)

### ISSUE THREAD

**Issue by ranjanmanish95** [cortezaproject/corteza-server#168]
@darh @vicpatel @petergrlica 
**Describe the bug**
I tried to set up the 2020.9 version corteza. Although my containers are up and running healthy when i tried to sign up this error (Error: failed to complete request due to internal error) shows me on the signup page of corteza.

I am attaching the docker-compose.yml file and .env file here:

**Docker-Compose.yml**
version: '3.5'

services:
  webapp:
    image: cortezaproject/corteza-webapp:${VERSION}
    restart: on-failure
    depends_on: [ server ]
    networks: [ proxy ]
    environment:
      # VIRTUAL_HOST helps NginX proxy route trafic for specific virtual host to
      # this container
      VIRTUAL_HOST:     ${DOMAIN}
      # This is needed only if you are using NginX Lets-Encrypt companion
      # (see docs.cortezaproject.org for details)
      LETSENCRYPT_HOST: ${DOMAIN}
      # Monolith API settings informs webapp autoconfiguration script that we're running
      # a monolith API server.
      MONOLITH_API: "true"

  server:
    image: cortezaproject/corteza-server-monolith:${VERSION}
    restart: on-failure
    env_file: [ .env ]
    depends_on: [ db, corredor ]
    networks: [ proxy, internal ]
    # Uncomment to use local fs for data persistence
    # volumes: [ "./data/server:/data" ]
    environment:
      # VIRTUAL_HOST helps NginX proxy route traffic for specific virtual host to
      # this container
      # This value is also picked up by initial boot auto-configuration procedure
      # If this is changed, make sure you change settings accordingly
      VIRTUAL_HOST: api.${DOMAIN}
      # This is needed only if you are using NginX Lets-Encrypt companion
      # (see docs.cortezaproject.org for details)
      LETSENCRYPT_HOST: api.${DOMAIN}

  corredor:
    image: cortezaproject/corteza-server-corredor:${VERSION}
    networks: [ internal ]
    restart: on-failure
    env_file: [ .env ]
    # In case you do not follow the usual setup with $DOMAIN and api.$DOMAIN, please see the
    # Documentation on how you can configure Corredor API endpoints with 
     CORREDOR_EXEC_CSERVERS_API_BASEURL_TEMPLATE,
    # CORREDOR_EXEC_CSERVERS_API_HOST and other CORREDOR_EXEC_CSERVERS_* variables.

  db:
    # MySQL Database
    # See https://hub.docker.com/r/percona/percona-server for details
    image: percona:8.0
    restart: on-failure
    # Uncomment to use local fs for data persistence
    # volumes: [ "./data/db:/var/lib/mysql" ]
    environment:
      # To be picked up by percona image when creating the database
      # Must match with DB_DSN settings inside .env
      #
      # Warning: these are values that are only used on 1st start
      #          if you want to change it later, you need to do that
      #          manually inside db container
      MYSQL_DATABASE: dbname
      MYSQL_USER:     dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_RANDOM_ROOT_PASSWORD: random # docker-compose logs db |grep "GENERATED ROOT PASSWORD"
    healthcheck: { test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"], timeout: 20s, retries: 10 }
    networks: [ internal ]

networks:
  internal: {}
  proxy: { external: true }

**.env**
########################################################################################################################
# docker-compose supports environment variable interpolation/substitution in compose configuration file
# (more info: https://docs.docker.com/compose/environment-variables)

########################################################################################################################
# General settings
DOMAIN=crm.fincuro.com
VERSION=2020.9

########################################################################################################################
# Database connection

DB_DSN=dbuser:dbpass@tcp(db:3306)/dbname?collation=utf8mb4_general_ci

########################################################################################################################
# Authentication

# Secret to use for JWT token
# Make sure you change it (>30 random characters) if
# you expose your deployment to outside traffic
 AUTH_JWT_SECRET=this-is-only-for-demo-purpose--make-sure-you-change-it-for-production

########################################################################################################################
# SMTP (mail sending) settings

# Disable email confirmation for sign-up protocol to allow more seamless setup without the need
# for SMTP Server
#PROVISION_SETTINGS_AUTH_INTERNAL_SIGNUP_EMAIL_CONFIRMATION_REQUIRED=false

# Point this to your local or external SMTP server
SMTP_HOST=smtp.gmail.com:587
SMTP_USER=*************
SMTP_PASS=***********
SMTP_FROM='"******* ***" <***************>'

# Corredor service settings

# Corredor address is used in Corredor service for grpc server configuration
# and inside Server for configuring corredor gRPC client with location for corredor server
# If these two values are different in your environment for
CORREDOR_ADDR=corredor:80

**Expected behavior**
While signup i should be into my corteza instance but i m getting the failed to complete request due to internal error. Also i added configuration variables also but was nt able to get in due to same authentication error. While checking server logs it was not showing any particular error. Attaching the screenshot of the same below.

**Screenshots**
![Screenshot (84)](https://user-images.githubusercontent.com/33874102/114461823-db1cde00-9bff-11eb-9234-3ede3d20e390.png)
![Screenshot (85)](https://user-images.githubusercontent.com/33874102/114462768-1ec41780-9c01-11eb-86aa-af670af4158b.png)

Please guide me for the cause of this error as i m completely lost here.
Thanks

**Comment by darh** [comment]
Can you show me browser console errors and/or problematic network request from browser?

**Comment by ranjanmanish95** [comment]
@darh 
There is no specific errors which are shown in browser console. Neither in network nor in console. Url is crm.fincuro.com/auth/signup. Every request and response code is 200. i checked console after filling data and click on signup button. Data is also shown there with status code 200.
![Screenshot (86)](https://user-images.githubusercontent.com/33874102/114503053-573c1380-9c4a-11eb-89aa-22c2cd35600b.png)
![Screenshot (88)](https://user-images.githubusercontent.com/33874102/114506331-417d1d00-9c4f-11eb-9c34-95b7432740b2.png)
![Screenshot (90)](https://user-images.githubusercontent.com/33874102/114503147-75a20f00-9c4a-11eb-915b-ee74ab2cce16.png)

While checking issues on console it is showing two issues in particular:
1. autocomplete attribute must be used correctly
2. Form elements must have labels

![Screenshot (95)](https://user-images.githubusercontent.com/33874102/114503980-c0705680-9c4b-11eb-9a9e-d47dfc5767b2.png)
![Screenshot (94)](https://user-images.githubusercontent.com/33874102/114503997-c8c89180-9c4b-11eb-82d6-7a63dbb17fbc.png)

**Comment by darh** [comment]
Jeez, that's a loot of screenshots. Thank you for pointing out albeit unrelated issues with the form. We'll look into it.

How about if you enable logging and increase it's level and try to figure out what is going on:
```
LOG_LEVEL=debug
LOG_DEBUG=true
```

Please make sure you reload your server (`docker-compose up -d` or equivalent).

_Not sure if you knew, pastebin or github gist are much better tools for sharing blocks of texts like logs etc than uploading screenshots here + it allows me to quickly search through them_

**Comment by ranjanmanish95** [comment]
@darh 
Finally I figured out the issue. Issue was that our smtp credentials have got expired. Thats the same issue i got with other instances too since I have used same smtp credentials everywhere which I setup with gmail. 

![Screenshot (99)](https://user-images.githubusercontent.com/33874102/114660945-c598d880-9d13-11eb-89b1-d0cd00aab01a.png)

![Screenshot (100)](https://user-images.githubusercontent.com/33874102/114661383-874fe900-9d14-11eb-8565-8e7941ab6e76.png)

Now I have not tested with new smtp credentials till now since its not ready but I m sure that its the same issue.
Will close this once I test my instance with valid smtp credentials and will inform you. 
Thanks and Regards

**Comment by ranjanmanish95** [comment]
@darh 
The above issue is fixed. I set up a new smtp server and added the credentials in the .env file. Deployed my instance again and refresh it and it worked.
I am closing this ticket.
Thanks and Regards.
![Screenshot (103)](https://user-images.githubusercontent.com/33874102/114684648-bd9a6200-9d2e-11eb-93ae-afe242d599d4.png)
