### ISSUE TITLE
Help with compilation!

### ISSUE THREAD

**Issue by akshaykumararavindan** [cortezaproject/corteza-server#169]
**Describe the bug**
I ran `make codegen` and then ran `make realize` to launch a local dev server. After which  the dev server doesn't start this is the error log:
`{"level":"info","ts":1618375469.2147589,"caller":"service/service.go:131","msg":"initializing store","path":"var/store (defaults to \"/var/store\")/compose"}`
`{"level":"info","ts":1618375469.2221491,"caller":"provision/config.go:26","msg":"already provisioned, skipping full config import"}`
`Error: store encoder prepare rbac rule []: role unresolved [everyone]`
`Usage:
  corteza-server serve-api [flags]`

`Aliases:
  serve-api, serve`

``Flags:
  -h, --help   help for serve-api``

`store encoder prepare rbac rule []: role unresolved [everyone]`

**To Reproduce**
I followed these steps:
* make codegen
* make realize

**Expected behavior**
A local development server to start.

**Additional context**
I was just making very minor changes so that SMTP settings from the env files are stored into the DB on first load of the application (not sure if that is a good feature)

**Comment by darh** [comment]
Can you show me contents of your `.env` file?

hint1: no need to codegen if you did not do any changes (to templates, yaml files).
hint2: realize => watch (realize was an old tool we used for reloading server on code change, it's still there but deprecated, watch is used now as it's more generic)

**Comment by akshaykumararavindan** [comment]
@darh Sure. Here:

```
# Corteza configuration

# Note: default docker image without any extra command will
# force :80 via flag and override anything you set here
HTTP_ADDR=:3001

# SMTP configuration
# For dev environment, run mailhog (`make mailhog.up`), set SMTP_HOST to `localhost:1025`
# and visit localhost:8025.
# SMTP_HOST=localhost:1025
# SMTP_USER=
# SMTP_PASS=
# SMTP_FROM="Corteza" <info@local.cortezaproject.org>


# JWT Secret, shared among all services.
# If not set, random value will be set every time you reset the service
#AUTH_JWT_SECRET=

# JWT expiration (duration, default: '720h', 30 days)
#AUTH_JWT_EXPIRY=

# Debug level you want to use (anything equal or lower than that will be logged)
# Values: debug, info, warn, error, panic, fatal
LOG_LEVEL=info

# Timeout for internal HTTP client
HTTP_CLIENT_TIMEOUT=30s

# Allow usage of insecure hosts (self-signed, expired certificates)
HTTP_CLIENT_TSL_INSECURE=false

# Log HTTP requests
HTTP_LOG_REQUESTS=true

HTTP_WEBAPP_ENABLED=true
HTTP_WEBAPP_LIST="admin,one,workflow,compose"

localhost:3001

# AUTH_BASE_URL=http://localhost:3001/auth


# Monitoring log interval
MONITOR_INTERVAL=5min

# Database to use
# DB_DSN=corteza:corteza@tcp(localhost:3306)/corteza?collation=utf8mb4_general_ci
DB_DSN=postgres://postgres:postgres@localhost:5432/corteza?sslmode=disable

# Log database queries?
#DB_LOGGER=false

# Logging level we want to use (values: debug, info, warn, error, dpanic, panic, fatal)
LOG_LEVEL=info

# Enable debug logger (more verbose,
LOG_DEBUG=false

########################################################################################################################
# Storage configuration

# Local, plain storage path:

# General all-in-one
STORAGE_PATH=var/store (defaults to "/var/store")

# or separate path by service (Docker default values):
#COMPOSE_STORAGE_PATH=/data/compose
#SYSTEM_STORAGE_PATH=/data/system

# Min.io:
# Storage to minio backend is activated when MINIO_ENDPOINT is set
#
# If you are in development environemnt and using `make minio.up` for testing,
# your min.io instance is most likely listening on localhost
# (inspect `Makefile` for details)
#MINIO_ENDPOINT=localhost:9000

# Access & secret key
# These keys are used by Min.io Docker container as well
#MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
#MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# Per-service buckets (default values)
#COMPOSE_MINIO_BUCKET=compose
#SYSTEM_MINIO_BUCKET=system

# Strict mode:
# When true, it does not create un-existing buckets
#MINIO_STRICT=false

#######################################################################################################################

#
# Federation - warning, this is still an experimental feature
#
FEDERATION_ENABLED=false
FEDERATION_HOST=localhost:80
FEDERATION_LABEL=Federation host 1

# Sync settings - paging and sync delay
FEDERATION_SYNC_STRUCTURE_MONITOR_INTERVAL=2m
FEDERATION_SYNC_DATA_MONITOR_INTERVAL=60s
FEDERATION_SYNC_DATA_PAGE_SIZE=100

# This needs to be one per page for architectural reasons for now
FEDERATION_SYNC_STRUCTURE_PAGE_SIZE=1

```

**Comment by akshaykumararavindan** [comment]
> Can you show me contents of your `.env` file?
> 
> hint1: no need to codegen if you did not do any changes (to templates, yaml files).
> hint2: realize => watch (realize was an old tool we used for reloading server on code change, it's still there but deprecated, watch is used now as it's more generic)

Understood. I'm just used to launching the local dev server with `make realize`, will adapt to using `make watch` from now on

**Comment by akshaykumararavindan** [comment]
@darh Not sure what the issue was, but once I removed the local DB tables (Postgres) which I was using and let the server create the tables, things started to work fine. Is there a way for you to tell me what I might have done to get that error?
