### ISSUE TITLE
could not load corredor server scripts","error":"rpc error: code = DeadlineExceeded desc 

### ISSUE THREAD

**Issue by ranjanmanish95** [cortezaproject/corteza-server#170]
@darh 
**Describe the bug**

*{"level":"error","ts":1617686346.9232132,"logger":"corredor","caller":"corredor/service.go:850","msg":"could not load corredor client scripts","error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp 172.23.0.2:80: connect: connection refused"","stacktrace":"github.com/cortezaproject/corteza-server/pkg/corredor.(service).loadClientScripts\n\t/drone/src/pkg/corredor/service.go:850"}

I am getting above error while checking my server container logs. Corteza version is 2020.9 although the version was 2020.6 earlier but there also i was getting the same grpc error.
Although i checked the troubleshooting documentation of 2021.3 but its written to check the changes made to the configuration if problem still persists.
I changed the configuration of .env file also but it is not working. Below is the .env file which i m using.

# .env

#General settings
DOMAIN=crm.fincuro.com
VERSION=2020.9

#Database connection
DB_DSN=dbuser:...removed by dev...@tcp(db:3306)/dbname?collation=utf8mb4_general_ci

#Authentication
#Secret to use for JWT token
 AUTH_JWT_SECRET=...removed by dev...

#Corredor Settings
 CORREDOR_ENABLED=true
 CORREDOR_LOG_PRETTY=true
 CORREDOR_DEBUG=true

#for SMTP Server
 PROVISION_SETTINGS_AUTH_INTERNAL_ENABLED=true

#Point this to your local or external SMTP server
SMTP_HOST=...removed by dev...
SMTP_USER=...removed by dev...
SMTP_PASS=...removed by dev...
SMTP_FROM=...removed by dev...

#Corredor service settings
CORREDOR_ADDR=corredor:80
CORREDOR_EXT_SEARCH_PATHS=/extensions:/extensions/*:/corredor/crm-yarn-extension

**Expected behavior**
Our Server container should call and transport our server scripts on the event bus. Logs should not have shown grpc connection error.

**Screenshots**
![Screenshot (108)](https://user-images.githubusercontent.com/33874102/115021329-769ca000-9ed9-11eb-96d4-2ae6791d58ab.png)
![Screenshot (107)](https://user-images.githubusercontent.com/33874102/115021491-a64ba800-9ed9-11eb-8675-1c67129ab22c.png)

This was the same issue i was experiencing in 2020.6. Please throw some light on this.
Thanks and Regards

**Comment by ranjanmanish95** [comment]
@darh 
I updated my .env file and it is now as follows:

# .env
#Authentication
#you expose your deployment to outside traffic
 AUTH_JWT_SECRET=...removed by dev...

#Corredor Settings
 CORREDOR_ENABLED=true
 CORREDOR_LOG_PRETTY=true
 CORREDOR_DEBUG=true
 CORREDOR_MAX_BACKOFF_DELAY=2 minute
 CORREDOR_DEFAULT_EXEC_TIMEOUT=2 minute
 CORREDOR_LIST_TIMEOUT=4 second
 CORREDOR_LIST_REFRESH=4 second
 GRPC_CLIENT_LOG=true
 LOG_LEVEL=debug
 LOG_DEBUG=true

#SMTP (mail sending) settings
#Disable email confirmation for sign-up protocol to allow more seamless setup without the need
#for SMTP Server
#PROVISION_SETTINGS_AUTH_INTERNAL_SIGNUP_EMAIL_CONFIRMATION_REQUIRED=false
 PROVISION_SETTINGS_AUTH_INTERNAL_ENABLED=true

#Point this to your local or external SMTP server
SMTP_HOST=...removed by dev...
SMTP_USER=...removed by dev...
SMTP_PASS=...removed by dev...
SMTP_FROM=...removed by dev...

#Corredor service settings
CORREDOR_ADDR=corredor:80
CORREDOR_EXT_SEARCH_PATHS=/extensions/*:/corredor/crm-yarn-extension/crm-yarn-extension

Although i am getting the same error but i set the debug log configuration hence attaching the screenshots:
![Screenshot (116)](https://user-images.githubusercontent.com/33874102/115226512-f2425b00-a12c-11eb-8854-d2c98b0ce2ce.png)
![Screenshot (117)](https://user-images.githubusercontent.com/33874102/115226516-f40c1e80-a12c-11eb-90f7-281b8d64fcd2.png)

Same error is showing even when i increased the corredor scripts timeout through configuration. 
Please guide me through this. 
Thanks and Regards

**Comment by tjerman** [comment]
@ranjanmanish95
First off, I would strongly advise you to change your secrets (the JWT and SMTP secrets).

In regards to your question, with the provided context I can't provide any help other than -- it works fine; the Corredor server may still be unavailable before the Corteza server starts -- the error state may be a bit extreme, but it's intentional.
At the bottom of your last log image, you can see that the scripts were registered at the end.

Did you correctly expose your scripts to the Corredor server? Are they showing in the admin panel?

___

I will close this issue as it's resolved. If you need help with defining automation scripts feel free to write on our [forum](https://forum.cortezaproject.org/)

Perhaps you might prefer our new [workflows feature](https://docs.cortezaproject.org/corteza-docs/2021.3/integrator-guide/workflows/index.html) as it provides a GUI to implement custom business logic.
