### ISSUE TITLE
Updating Email templates

### ISSUE THREAD

**Issue by akshaykumararavindan** [cortezaproject/corteza-server#171]
**Describe the bug**

Provision > 002_templates

Updates not applying to database of deployment on subsequent updates of "auth.yaml" rolled out into production (CI/CD)

**To Reproduce**

```
1) Set ".env" PROVISION_ALWAYS=true
2) Update content of email template in "auth.yaml"
3) Rebuild -> Deploy
```

**Expected behavior**

Email templates (as stored in PostgreSQL) would be updated (reflecting changes in "auth.yaml" & PROVISION_ALWAYS=true)

**Screenshots**

Not applicable.

**Additional context**

What part of source code is the applicable logic or conditional evaluation of deploying updates in application code out to configuration settings held in the DB on a deployment system?

**Comment by akshaykumararavindan** [comment]
I faced a new issue, wherein the during the provision process I got this error message: "store encoder prepare compose record [Department]: provided module namespace ID does not match filter namespace ID". @darh could you please shed some light on this

**Comment by darh** [comment]
\cc @tjerman

**Comment by tjerman** [comment]
@akshaykumararavindan

> Provision > 002_templates
> 
> Updates not applying to database of deployment on subsequent updates of "auth.yaml" rolled out into production (CI/CD)

The provision step will not update existing templates or any other resources (such as a namespace or a module). The main reason for this is that it could overwrite custom modifications.
If you wish to forcefully update the template via YAML files, you can run the import CLI command (check the CLI reference). They can also be modified manually via the UI on the admin panel webapp.

> I faced a new issue, wherein the during the provision ...

* What version are you running?
* Did you upgrade from another version (if so, which)?
* What modifications/additions have you done to the original provision files?
* Can you share your `701_service-solution/1500_record_settings.yaml` file or the entire set of provision files?
* Have you changed/removed the `crm` and `service-solution` namespaces?

**Comment by akshaykumararavindan** [comment]
> What version are you running?

2021.3.0

> Did you upgrade from another version (if so, which)?

2020.12.0. (I don't really have any data, so I didn't bother doing a proper migration, I just deleted the old version) 

> What modifications/additions have you done to the original provision files?

Mostly rbac and application icons to svg, I noticed that the icons were using png.

> Can you share your 701_service-solution/1500_record_settings.yaml file or the entire set of provision files?

```
namespace: service-solution
records:
  Department:
    - (envoy): { skipIf: "!missing" }
      values:
        Name: "Service"
        HourCost: "50"
  Settings:
    - (envoy): { skipIf: "!missing" }
      values:
        KBNextNumber: "1"
        DefaultCostPerHour: "50"
        DefaultTimeUpdate: "0.25"

```
> Have you changed/removed the crm and service-solution namespaces?

No.

To provide additional context, I will attach the error logs below: 

```
{"level":"info","ts":1619050429.8555508,"caller":"service/service.go:147","msg":"initializing store","path":"/data/system"}
{"level":"info","ts":1619050429.856347,"caller":"service/service.go:131","msg":"initializing store","path":"/data/compose"}
{"level":"info","ts":1619050429.8670905,"caller":"provision/config.go:70","msg":"importing all configs","paths":"provision/*"}
{"level":"info","ts":1619050429.867133,"caller":"provision/config.go:72","msg":"provisioning from path","path":"provision/000_base"}
{"level":"info","ts":1619050429.867881,"caller":"provision/config.go:72","msg":"provisioning from path","path":"provision/001_settings"}
{"level":"info","ts":1619050429.868856,"caller":"provision/config.go:72","msg":"provisioning from path","path":"provision/002_templates"}
{"level":"info","ts":1619050429.869434,"caller":"provision/config.go:72","msg":"provisioning from path","path":"provision/003_auth"}
{"level":"info","ts":1619050429.8695893,"caller":"provision/config.go:72","msg":"provisioning from path","path":"provision/101_applications"}
{"level":"info","ts":1619050429.8699841,"caller":"provision/config.go:72","msg":"provisioning from path","path":"provision/200_federation"}
{"level":"info","ts":1619050429.870307,"caller":"provision/config.go:72","msg":"provisioning from path","path":"provision/300_automation"}
{"level":"info","ts":1619050429.8708832,"caller":"provision/config.go:72","msg":"provisioning from path","path":"provision/700_crm"}
{"level":"info","ts":1619050430.0327299,"caller":"provision/config.go:72","msg":"provisioning from path","path":"provision/701_service-solution"}
Error: store encoder prepare compose record [Department]: provided module namespace ID does not match filter namespace ID
Usage:
  corteza-server serve-api [flags]

Aliases:
  serve-api, serve

Flags:
  -h, --help   help for serve-api

store encoder prepare compose record [Department]: provided module namespace ID does not match filter namespace ID
```

**Comment by akshaykumararavindan** [comment]
@tjerman I have got another question regarding the date setting in the CRM. How would I change the date format from mm/dd/yyyy to YYYY-MM-DD

**Comment by tjerman** [comment]
Can you try with the newer 2021.3.2 version (it includes a few patches).

> 2020.12.0. (I don't really have any data, so I didn't bother doing a proper migration, I just deleted the old version)

If you've reused the same database it might be possible that it entered some strange state. Worth a shot to recreate the database.

> I have got another question regarding the date setting in the CRM. How would I change the date format from mm/dd/yyyy to YYYY-MM-DD

I'm guessing you're talking about the date input box. It uses whatever bootstrap uses (probably the current locale but don't quote me on this) and can't be changed at the moment.
If you're talking about the date display, there is a format option in the field configurator.

**Comment by akshaykumararavindan** [comment]
> If you've reused the same database it might be possible that it entered some strange state. Worth a shot to recreate the database.

It worked. Thanks.
