### ISSUE TITLE
Client authentication fails when using grant type = client credentials

### ISSUE THREAD

**Issue by tbvgl** [cortezaproject/corteza-server#175]
I'm trying to use the new OAuth2 flow with Corteza 2021.3.2 and Postman. The authentication flow using the grant type authorization_code works fine but using the grant type client_credentials doesn't work for me.

**That's the auth client in Corteza:**

![postman_corteza01](https://user-images.githubusercontent.com/57117197/116420359-3248c280-a83e-11eb-8f60-e3980c2dca9c.PNG)

**That's my Postman setup**

![postman01](https://user-images.githubusercontent.com/57117197/116420432-412f7500-a83e-11eb-951c-8627e4ee5db9.PNG)

**And that's the Postman console**

![postman_log](https://user-images.githubusercontent.com/57117197/116420493-4c82a080-a83e-11eb-919c-721e7ebb7801.PNG)

I tried sending the client credentials in the body as well as Basic Auth header. I tried it with setting a redirect url in Corteza and without. I'm stuck here and help would be highly appreciated. 

I checked the updated docs here https://github.com/cortezaproject/corteza-docs/commit/4358cc169595275544b23aa39f4537397b4950bb but couldn't find a solution to the problem either. 

**ENV**

```
###############################################################################>
# docker-compose supports environment variable interpolation/substitution in co>
# (more info: https://docs.docker.com/compose/environment-variables)

###############################################################################>
# General settings
DOMAIN=xxx
VERSION=2021.3.2

###############################################################################>
# Database connection

DB_DSN=corteza:xxx@tcp(db:3306)/xxx?collation=utf8mb4_gener>

###############################################################################>
# Server settings

# Serve Corteza webapps alongside API
HTTP_WEBAPP_ENABLED=true

# Send actionlog to container logs as well
# ACTIONLOG_DEBUG=true

# Uncomment for extra debug info if something goes wrong
# LOG_LEVEL=debug

# Use nicer and colorful log instead of JSON
# LOG_DEBUG=true

###############################################################################>
# Authentication

# Secret to use for JWT token
# Make sure you change it (>30 random characters) if
# you expose your deployment to outside traffic
AUTH_JWT_SECRET=xxx

###############################################################################>
# SMTP (mail sending) settings

# Point this to your local or external SMTP server
SMTP_HOST=smtp.sendgrid.net:2525
SMTP_USER=apikey
SMTP_PASS=xxx
SMTP_FROM='"xxx" <xxx>'
```

**docker-compose.yaml**

```
version: '3.5'

services:
  server:
    image: cortezaproject/corteza-server:${VERSION}
    restart: always
    env_file: [ .env ]
    depends_on: [ db, corredor ]
    networks: [ proxy, internal ]
    # Uncomment to use local fs for data persistence
    volumes: [ "./data/server:/data" ]
    environment:
      # VIRTUAL_HOST helps NginX proxy route trafic for specific virtual host to
      # this container
      VIRTUAL_HOST:     ${DOMAIN}
      # This is needed only if you are using NginX Lets-Encrypt companion
      # (see docs.cortezaproject.org for details)
      LETSENCRYPT_HOST: ${DOMAIN}

  corredor:
    image: cortezaproject/corteza-server-corredor:${VERSION}
    networks: [ internal ]
    restart: always
    env_file: [ .env ]

  db:
    # MySQL Database
    # See https://hub.docker.com/r/percona/percona-server for details
    image: percona:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes: [ "./data/db:/var/lib/mysql" ]
    environment:
      # To be picked up by percona image when creating the database
      # Must match with DB_DSN settings inside .env
      #
      # Warning: these are values that are only used on 1st start
      #          if you want to change it later, you need to do that
      #          manually inside db container
      MYSQL_DATABASE: xxx
      MYSQL_USER:     xxx
      MYSQL_PASSWORD: xxx
      MYSQL_RANDOM_ROOT_PASSWORD: random # docker-compose logs db | grep "GENER>
    healthcheck: { test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"], time>
    networks: [ proxy, internal ]
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

networks:
  internal: {}
  proxy: { external: true }
```

**Comment by darh** [comment]
@tbvgl you're correct, this is broken atm. I already have patch ready. Will push & update this issue in next few days.

**Comment by tbvgl** [comment]
@darh awesome, thanks for the fast response. I'll wait or if you want to send me the patch so that I can help testing feel free to do so.

**Comment by darh** [comment]
Fixes were pushed to `2021.3.x` and `2021.6.x` branch. Release (docker image) should be pushed in couple of days, next week most likely.

**Comment by tbvgl** [comment]
thanks @darh I'll test today and report back.

**Comment by tbvgl** [comment]
So I pulled the new code and tested again. 
I'm getting a different error now.

**Corteza**

![corteza](https://user-images.githubusercontent.com/57117197/116613652-3d344d80-a939-11eb-9ea1-5ef8e89cd25a.PNG)

**Postman**

![Unbenannt](https://user-images.githubusercontent.com/57117197/116613779-6359ed80-a939-11eb-9bc6-5763ad3ee919.PNG)

**Postman Console/Error**

```
POST /auth/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic xxx
User-Agent: PostmanRuntime/7.28.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 82cb4e6d-797e-453c-b27a-44363379e34c
Host: hub.gridpane.com
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 49
 
grant_type=client_credentials&scope=profile%20api
 
HTTP/1.1 500 Internal Server Error
Server: nginx/1.19.3
Date: Thu, 29 Apr 2021 18:42:54 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 55
Connection: keep-alive
Cache-Control: no-store
Pragma: no-cache
Vary: Origin
X-Ratelimit-Limit: 60
X-Ratelimit-Remaining: 60
X-Ratelimit-Reset: 1619721780
X-Request-Id: 66ffed7508f8/jE3Lvg1rta-000800
Strict-Transport-Security: max-age=31536000
 
{"error":"auth client security configuration invalid"}
```

I saw that the error gets triggered here and must have something to do with the user impersonation but I'm not sure how to work around that or fix that.

https://github.com/cortezaproject/corteza-server/commit/b245726c9b0308dc87726a17832c127afe55b228
```
	if gt == oauth2def.ClientCredentials {
		// Authenticated with client credentials!
		//
		// We'll use info from client security
		if client.Security == nil || client.Security.ImpersonateUser == 0 {
			return h.tokenError(w, errors.Internal("auth client security configuration invalid"))
		}

		tgr.UserID = strings.Join(append(
			[]string{fmt.Sprintf("%d", client.Security.ImpersonateUser)},
			client.Security.ForcedRoles...,
		), " ")
	}
```

**Comment by darh** [comment]
I see. Unfortunately one of the admin frontend component was not updated with this patch
The problem you're seeing here is that with `client_credentials` auth flow you have to set the user you want to use with the client. This is mandatory.

Can I ask you to update `auth_clients` table manually for now?
You'll see security column with JSON serialized data. You should update/set it to something like this: 
```json
{"impersonateUser": "96322685868441659"}
```

Use the ID of one of your users.

**Comment by tbvgl** [comment]
thanks @darh it's working after updating the db.
