### ISSUE TITLE
CSV Import fails with "wrong number of fields" error

### ISSUE THREAD

**Issue by akshaykumararavindan** [cortezaproject/corteza-server#177]
**Describe the bug**
When trying to import a csv file, the process always fails with:
```
Object { message: "failed to complete transaction: store encoder encode compose record [229049919019679759]: record on line 100: wrong number of fields" }
```
I generated a junk CSV file with the same record repeated for 1000 times (1000 records), but I can only import 98 records at once then the import fails with error decsribed above.

**To Reproduce**
[blah - blah - 1.csv](https://github.com/cortezaproject/corteza-server/files/6404437/blah.-.blah.-.1.csv)
Create a module with the fields in the CSV and try importing the data.

**Expected behavior**
For all the records to be imported successfully.

**Screenshots**
![test](https://user-images.githubusercontent.com/41286878/116678993-572f6800-a9ed-11eb-95c5-7239c36f4721.png)

**Additional context**
I use postgres locally (not sure if this is an issue cause by postgres).
UPDATE: The import works fine in 2020.12.x, but not in 2021.6.x.

**Comment by akshaykumararavindan** [comment]
@tjerman Would you be able to shed some light on this?

**Comment by tjerman** [comment]
I'm looking into it; there seems to be an issue with some buffers that cut off the data

**Comment by tjerman** [comment]
@akshaykumararavindan I've pushed a patch to address this issue on both 2021.3.x and 2021.6.x branches. There was some strange interaction between the buffers and the CSV parsing library and the content got cut off at x.

If you're running Corteza via Docker, you'll need to wait for the next patch release; if you're running it outside of docker, then pull the changes.

2021.6.x is the in-development (unstable) version and I would suggest you use the latest 2021.3.x version.
