### ISSUE TITLE
Update fails on old records if recordSelector gets removed from module

### ISSUE THREAD

**Issue by tnissen375** [cortezaproject/corteza-server#179]
Update of records fails with 502 when an recordSelector is removed from module.

**To Reproduce**
Create a Module with some fields and a record selector of another module. 
Populate some records. Go back to the module and remove the recordsSelector field. 
The formely created records of the module are still there but can not be edited anymore. (502) They can be deleted but not updated.

**Expected behavior**
Old records should still work if fields get added or removed from modules. 

**Screenshots**
Hopefully not necessary ;)

**Additional context**
Version: 2021.3.2

**Comment by darh** [comment]
Is this still an issue?
