### ISSUE TITLE
errors: workflow for selected records automation

### ISSUE THREAD

**Issue by leenchou1981** [cortezaproject/corteza-server#193]
i create a workflow for record list. then when I select some records in record list page and triger a workflow, the following http request body will be send to corteza server: 
{"stepID":"32","input":{"selected":{"@value":["232135346937135106","232135372572721154"],"@type":"Any"},"filter":{"@value":{"limit":20,"sort":"id","filter":"","moduleID":"231119551654264834","namespaceID":"227170092884951042","query":"","deleted":0,"incPageNavigation":false,"incTotal":false,"total":3},"@type":"Any"}}}

but, error will happen,  the input of **filter** and **selected** is not been parsed as following saw in logs.

{"filter": {"@type": "Any", "@value": {}}, "selected": {"@type": "Any", "@value": {}}, "eventType": {"@type": "String", "@value": "onManual"}, "resourceType": {"@type": "String", "@value": "system"}}

**Comment by darh** [comment]
Is this still an issue? Can you upgrade to the latest 2021.3.x and check again please.
