### ISSUE TITLE
Active workflows gets executed even if deleted

### ISSUE THREAD

**Issue by techu** [cortezaproject/corteza-server#198]
**Describe the bug**
Active workflows gets executed even if deleted

**To Reproduce**
1) Create and workflow to modify record with composeRecord Trigger and enable it.
2) Insert a record to check if workflow is enabled and working.
3) Delete the workflow.
4) Insert another record and you will see that the workflow still got executed even if it was deleted.

**Expected behavior**
Wordflow should not executed if deleted.

**Current Workaround**
Open deleted workflow from admin app.
Disable the workflow or clear the workflow content.

**Comment by darh** [comment]
Thank you for reporting the issue and apologies for the late response. 
Fixed and will be part of the next (patch) release.
