### ISSUE TITLE
How to disclose a potential security issue?

### ISSUE THREAD

**Issue by zidingz** [cortezaproject/corteza-server#199]
Hey there,

As there isn't a SECURITY.md or contact address in your repository, I am not sure how to contact you regarding a potential security issue.

Would you kindly provide an email so I can send you the details? Else, simply add a SECURITY.md file with an e-mail to your repository. GitHub recommends this as the best way to ensure security issues are responsibly disclosed.

Look forward to hearing from you, thanks!

**Comment by tjerman** [comment]
Hi,

You can send me an email at tomaz.jerman@crust.tech and I'll escalate it further if needed.
We'll include a SECURITY.md sometime before the next release.

Thank you for properly handling this type of issue!

**Comment by zidingz** [comment]
Awesome, thanks. Dropping you an email now 😊
