### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [cortezaproject/corteza-server#201]
Hi, @darh @titpetric @vicpatel @petergrlica 

Few security vulnerability has been submitted through huntr .
Plz validate them 
https://huntr.dev/bounties/2-cortezaproject/corteza-server/
https://huntr.dev/bounties/3-cortezaproject/corteza-server/
https://huntr.dev/bounties/4-cortezaproject/corteza-server/
https://huntr.dev/bounties/5-cortezaproject/corteza-server/
Report is only visible to repo maintainer and reporter .

**Comment by tjerman** [comment]
Hi @ranjit-git
It's on our list and should be resolved before the next patch release sometime next week.

**Comment by ranjit-git** [comment]
@tjerman greate.
can you plz update the report status to valid there?
