### ISSUE TITLE
Set up .env and .yaml to use HOST database

### ISSUE THREAD

**Issue by zayn008** [cortezaproject/corteza-server#208]
I'm having issues running the Percona database and would prefer to use my host MariaDB installation. How do i configure the setup files to do this? and do I need to configure docker since it will be connecting outside of the docker environment

**Comment by chiragob** [comment]
for external DB connectin 
you need change DB_DSN in .env file
DB_DSN=dbuser:dbpass@tcp( < Your IP > :3306)/dbname?collation=utf8mb4_general_ci

**Comment by darh** [comment]
Is this still an issue?
