### ISSUE TITLE
GitHub login does not include required email

### ISSUE THREAD

**Issue by Beanow** [cortezaproject/corteza-server#21]
**Describe the bug**
"can not use profile data without an email"
from `https://api.latest.cortezaproject.org/system/auth/external/github/callback`
Is produced when trying the `latest.cortezaproject.org` installation with a GitHub account.

**To Reproduce**
Make sure you're logged out and proceed to https://latest.cortezaproject.org/auth/login
Then try to use a github account for logging in.

**Expected behavior**
Login should succeed.

**Screenshots**
n/a

**Additional context**
You may be requesting the wrong OAuth scope for the GitHub API.
[The code](https://github.com/cortezaproject/corteza-server/blob/7d21d68bba3fd43c743f5db8c6d6954a45c18323/system/auth/external/goth.go#L53) seems to request `email`, however [this document](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/) mentions `user:email`.

Going to my account at https://github.com/settings/applications it shows corteza has gotten "Access public information (read-only)", as opposed to some other apps which include "Access user email addresses (read-only)"

**Comment by darh** [comment]
Will take a look in a short while. I hope you can use other providers or internal auth meanwhile.

**Comment by darh** [comment]
Weirdly both versions worked (for me). I've changed it to `user:email` anyway (fee5c2be). ty.

**Comment by Beanow** [comment]
I'm assuming the change hasn't rolled out to https://latest.cortezaproject.org/auth/login yet.
But requesting `email` as the scope returns that error for me.
Have you revoked the application access from https://github.com/settings/applications to make sure it's actually a new OAuth connection in between tests?

**Comment by darh** [comment]
You are correct. In both cases.
corteza/latest will be updated in a couple of days.
