### ISSUE TITLE
Consume external APIs?

### ISSUE THREAD

**Issue by davidedpg10** [cortezaproject/corteza-server#221]
Hello guys, I think this is a great platform and I'm glad to see active development.
Is there any plans for being able to consume external APIs by any chance?
Say, hypothetically I wanted to create an application that consumed the https://catfact.ninja/ to display cat facts, is that planned?
Thank you

**Comment by tjerman** [comment]
If you wish to make requests to the external API, you can do so either via [automation scripts](https://docs.cortezaproject.org/corteza-docs/2021.3/integrator-guide/automation-scripts/index.html), or via [workflows](https://docs.cortezaproject.org/corteza-docs/2021.3/integrator-guide/workflows/index.html).

If you wish to receive requests from an external API (the API calls your Corteza) you can use the [API](https://docs.cortezaproject.org/corteza-docs/2021.3/integrator-guide/accessing-corteza/index.html), or define a [sink route](https://docs.cortezaproject.org/corteza-docs/2021.3/devops-guide/extension-requirements/sink-route.html) if you need additional request processing.

**Comment by tjerman** [comment]
@davidedpg10 would you be able to give me some feedback in regards to the documentation and how I could make my answer easier to extract from the docs?
