### ISSUE TITLE
Corteza Server workflow module breaks when trying to assign non-existent record field.

### ISSUE THREAD

**Issue by as-vspry** [cortezaproject/corteza-server#228]
**Describe the bug**

When using a workflow to update a field that does not exist on a record, the request to execute a workflow will hang on the server indefinitely. This causes all other workflow executions to also hang, causing both manual and automated jobs to fail. The only way to fix this is to restart the corteza server. My best guess is some error has occurred server-side that causes the workflow controller to get stuck. This issue also seems to ignore the HTTP_CLIENT_TIMEOUT and CORREDOR_EXEC_TIMEOUT server configuration settings as they are both set to default (30sec and 1min respectively) but the client's request will hang until the server is force-stopped.

**To Reproduce**

1. Create a workflow.
2. Assign the trigger to a compose record event (in my example I used onManual)
3. Create an expression that assigns any string to a field on a record that does not exist and link the trigger to this node (in my example record.values.Account_Assessed_Risk is the target, and "Low" is the expression)
4. Create a Compose Record Update type function and assign record as the value and link the expression above to this node
5. Create a terminator and link the above function to this node
6. Run the workflow using the green run arrow on the trigger; use an existing record id from any module you have created that does not have the field being tested (In my case it was a module named accounts) and make sure the module handle and workspace handles are correct.

The workflow should now hang instead of showing a green or red flow through the workflow. Running any other workflow including workflows known to work will hang as well. This same workflow will execute without error if the field referenced (Account_Assessed_Risk) does exist on the record.

**Expected behavior**
The workflow shows a red flow stopping at the record update type function, displays an error, and does not prevent other workflows from running.

**Additional context**
Here are the request and action logs from the server on the exec event of the workflow. There is no response log because the server has yet to respond to the request. We have all http and corredor logging configuration turned on in the server:
`{"level":"info","ts":1628127453.7162445,"logger":"http.rest","caller":"server/logger.go:43","msg":"HTTP request POST /api/automation/workflows/240078220244811778/exec","requestID":"----", "method":"POST","path":"/api/automation/workflows/240078220244811778/exec","size":37883,"remote":"----"}`

 `01:37:33.748        DEBUG        actionlog        service/module.go:374        looked-up for a Accounts        {"timestamp": "01:37:33.748", "requestOrigin": "api/rest", "requestID": "----", "actorIPAddr": "----", "actorID": ----, "resource": "compose:module", "action": "lookup", "severity": 6, "error": "", "description": "looked-up for a Accounts", "policy-match": true, "meta": {"module.ID":236450222564179970,"module.handle":"accounts","module.name":"Accounts","module.namespaceID":236450160874356738,"namespace.ID":236450160874356738,"namespace.name":"Pluto","namespace.slug":"pluto"}}`

 `01:37:33.768        DEBUG        actionlog        service/module.go:374        looked-up for a Accounts        {"timestamp": "01:37:33.768", "requestOrigin": "api/rest", "requestID": "----", "actorIPAddr": "----", "actorID": ----, "resource": "compose:module", "action": "lookup", "severity": 6, "error": "", "description": "looked-up for a Accounts", "policy-match": true, "meta": {"module.ID":236450222564179970,"module.handle":"accounts","module.name":"Accounts","module.namespaceID":236450160874356738,"namespace.ID":236450160874356738,"namespace.name":"Pluto","namespace.slug":"pluto"}}`

 `{"level":"debug","ts":1628127453.7854762,"logger":"actionlog","caller":"service/trigger.go:131","msg":"searched for matching triggers","timestamp":1628127453.7854335,"requestOrigin":"api/rest","requestID":"----" ,"actorIPAddr":"----","actorID":----,"resource":"automation:trigger","action":"search","severity":6,"error":"","description":"searched for matching triggers","policy-match":true,"meta":{}}`

Here is also an example workflow that reproduces the problem:
[broken-workflow-example.zip](https://github.com/cortezaproject/corteza-server/files/6935263/broken-workflow-example.zip)

**Comment by darh** [comment]
Some additional context: this was tested on 2021.3.8

@as-vspry with [2021.3.9](https://docs.cortezaproject.org/corteza-docs/2021.3/changelog/index.html) we fixed a few workflow bugs that caused Corteza to wait indef. 

`2021.3.10` is the last released version. Please upgrade and try again.
