### ISSUE TITLE
json response from Compose API

### ISSUE THREAD

**Issue by chiragob** [cortezaproject/corteza-server#239]
**Compose API request**
``` 
curl 'https://latest.cortezaproject.org/api/compose/namespace/88714882739863655/module/69055788899106833/record/245818552450285576' \
  -H 'authorization: Bearer < Token >' \
  --compressed
```
getting response as below
```
{"response":{"recordID":"245818552450285576","moduleID":"69055788899106833",
"values":[{"name":"AccountId","value":"103510931929038850"},
	  {"name":"Description"},{"name":"Email","value":"prueba@prueba.com"},
          {"name":"FirstName","value":"Prueba"},
          {"name":"LastName","value":"Contacto"},
          {"name":"RecordLabel","value":"Prueba Contacto (Mycorp Limited)"}],
"namespaceID":"88714882739863655",
"ownedBy":"231959844272209928",
"createdAt":"2021-08-23T19:47:55Z",
"createdBy":"231959844272209928",
"updatedAt":"2021-08-24T07:36:46Z",
"updatedBy":"245150435592110088",
"canUpdateRecord":true,"canDeleteRecord":true}}
```
my problem is if we want to display one or two fields from response we have to iterate "values" array and check every time field name and display in front-end.
main problem if module have 20-30 fields then need to iterate full array.

**Suggested output if possible**
```
{"response":{"recordID":"245818552450285576","moduleID":"69055788899106833",
"values":{
	   "AccountId":"103510931929038850",
	  "Email":"prueba@prueba.com",
          "FirstName":"Prueba",
          "LastName":"Contacto",
          "RecordLabel":"Prueba Contacto (Mycorp Limited)"
          "Multi-Value":[{"Value1"},{value2}]
	},
"namespaceID":"88714882739863655",
"ownedBy":"231959844272209928",
"createdAt":"2021-08-23T19:47:55Z",
"createdBy":"231959844272209928",
"updatedAt":"2021-08-24T07:36:46Z",
"updatedBy":"245150435592110088",
"canUpdateRecord":true,"canDeleteRecord":true}}
```
if possible values as json object except array so we easily display fields. 
and without disturb current response can we add extra parameter like "json-response" and get suggested response in same api.

**Comment by darh** [comment]
@chiragob there are functions & classes inside `corteza-js` that handle this (1st example) kind of payload and reformat it into something similar to what you suggested in the 2nd one.

It's not even that difficult to write simple stand-alone functionality that converts it.

I'm also not very keen to the name you suggested, as if the first response is not in json format?

**Comment by chiragob** [comment]
@darh i agrre with to simple to convert data.

let me give you one example one listing page it display 100 record per page and this module have 20-30 fields.
In listing page per row only 5 field will display which are comeing from "values" array.
so every row will iterate value array and display it.

i suggest you if "values" is json object insted of array then without iterate we can display value in each row. its eliminate conversion. 
for e.g record.values[< field name >]


I'm also not very keen to the name you suggested, as if the first response is not in json format? 
->>> i agree payload in JSON format but "values" key is array. i suggest you to API will provide "values" key in JSON format.
for e.g. 
```
...
"values":{
	   "AccountId":"103510931929038850",
	  "Email":"prueba@prueba.com",
          "FirstName":"Prueba",
          "LastName":"Contacto",
          "RecordLabel":"Prueba Contacto (Mycorp Limited)"
          "Multi-Value":[{"Value1"},{value2}]
	},
...
```

**Comment by darh** [comment]
So, someone has to do the dirty work of data filtering and reformatting. 
The only way to do this today is on the client side (frontend, web-app).

It's highly unlikely that we'll provide any parameters on the existing CRUD endpoints that will return payloads in a different format.

New (REST, GraphQL) endpoints that specialise in the (record) data retrieval are more likely to happen.

**Comment by chiragob** [comment]
It's highly unlikely that we'll provide any parameters on the existing CRUD endpoints that will return payloads in a different format. -->> ok, this is just suggestion.
