### ISSUE TITLE
Quotes but no invoice?

### ISSUE THREAD

**Issue by superdolt** [cortezaproject/corteza-server#249]
saw a quote feature. is there an invoice feature as well?

**Comment by darh** [comment]
You can create different modules (data structures) as you wish. Creating one for an invoice should not be a problem

**Comment by superdolt** [comment]
hi, any tutorials on how to create invoice?
any ready made modules?

**Comment by tjerman** [comment]
This is the documentation page that goes over the area in question -- https://docs.cortezaproject.org/corteza-docs/2021.3/integrator-guide/compose-configuration/index.html

This documentation page is an upgrade of the prior one, but it is still a draft (unpolished) -- https://docs.cortezaproject.org/corteza-docs/2021.3-draft/integrator-guide/compose-configuration/index.html
