### ISSUE TITLE
GOOS=windows GOARCH=amd64 go build -ldflags "-X github.com/cortezaproject/corteza-server/pkg/version.Version= " -o build/corteza-server--windows-amd64.exe cmd/corteza/main.go

### ISSUE THREAD

**Issue by zzhkiller** [cortezaproject/corteza-server#265]
Thanks for helping us to improve Corteza! We welcome all bug reports. Once we've verified and fixed your issue, we'll ping you in the comments to see if you can verify the fix.
We'll give you details on what version can be used to test the fix. Additionally, if you are interested in testing fixes that you ***didn't*** report, look for the issues with
the `status/to-test` label. You can pick any of these up for verification. ***You can delete this message portion of the bug report.***

**Describe the bug**

![image](https://user-images.githubusercontent.com/5735777/135076964-ff2f13d9-341d-4ff0-afe7-ecdec28cd79c.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by darh** [comment]
Hi @zzhkiller 

Can you please provide more details here... All I see is the text from our issue template

**Comment by darh** [comment]
No response, closing.
