### ISSUE TITLE
visit localhost/healthcheck FAIL ObjectStore/System: remove data/store/system/.healthcheck: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by danniel2016** [cortezaproject/corteza-server#277]
Problem description:
Running OS:Windows 10
Corteza-server version:2021.3.x
Running a demo corteza-server in windows 10,and visit the url localhost/healthcheck,the result is the following information.
FAIL ObjectStore/System: remove data/store/system/.healthcheck: The process cannot access the file because it is being used by another process.
FAIL ObjectStore/Compose: remove data/store/compose/.healthcheck: The process cannot access the file because it is being used by another process.

So how to solve it?

**Comment by darh** [comment]
My first bet would be that you misconfigured mounted volumes that are used for data store.

**Comment by danniel2016** [comment]
The following is my env file.
[conf.txt](https://github.com/cortezaproject/corteza-server/files/7329244/conf.txt)

**Comment by danniel2016** [comment]
I utilized the default data store configuration

**Comment by darh** [comment]
Can you share your docker-compose setup as well?

**Comment by danniel2016** [comment]
I ran the program in the windows terminal.I didn't use the docker-compose yaml file to setup this project.I pulled the project code from the github,and modify the config file called .env,then into the root directory,exec the command "make realize",that's all.This project must use docker-compose to setup in the windows environment?

**Comment by darh** [comment]
I can not answer you that. No one from the core backend team uses Windows and we can not offer support for native-windows deployments.

Not sure where your skills are or what you want to achieve but please share your findings (in form of a PR or a comment here) if you manage to get it working.

**Comment by danniel2016** [comment]
thank you very much.Just for convenient debugging interfaces in the windows,later I will debug in the linux environment.
