### ISSUE TITLE
cannot found the recently created workflow when adding the block

### ISSUE THREAD

**Issue by danniel2016** [cortezaproject/corteza-server#279]
After clicking the New Workflow button in the workflow panel,and then create a newly workflow.Finally,cannot find this newly workflow when adding to the block.

![image](https://user-images.githubusercontent.com/20633575/137074254-832d5fea-3569-404d-b893-ce7759e574ae.png)

The new created workflow not be found in the list.

**Comment by tjerman** [comment]
Would you mind writing down what resolved the issue? I would assume that either:

* you had to refresh the tab in order to load in a fresh list of workflows
* the workflow configuration wasn't valid/didn't define appropriate trigger configurations
