### ISSUE TITLE
[Project architecture design problem]  Entity persistence design

### ISSUE THREAD

**Issue by cabbage89** [cortezaproject/corteza-server#284]
Currently corteza can flexibly define models, but all models are stored in a table (column-to-row mode is not convenient for SQL queries), and each model cannot be mapped to a physical table in the database, which will be accumulated in the future After a lot of data, it will be bad.
I think a better way is to use [facebook ent](https://github.com/ent/ent), the model can still be defined flexibly, but the corresponding physical table is generated by the ORM in the database, so that it is easier to maintain

**Comment by darh** [comment]
Thank you for pointing us to fb ent @cabbage89. From the first glance it does not really solve the problem we're having. 

Wherever the data will be stored (this column-to-row now or physical tables later), they are always defined in what we call "module". The record storage layer should be defined in a way that it is 100% transparent to the services using it.
As the current plans look like, libs&tools we use right now sqlx, squirrel should cover all our needs.
