### ISSUE TITLE
SMTP_FROM ignored

### ISSUE THREAD

**Issue by bio58** [cortezaproject/corteza-server#288]
**Describe the bug**
An error is thrown when I try to create a new user, which send an email through SMTP using SMTP_FROM in the .env file.

**To Reproduce**
1. Install Corteza in a docker container using [the official documentation](https://docs.cortezaproject.org/corteza-docs/2021.9/devops-guide/index.html#_setup_your_file_structure_2).
2. Set SMTP settings in the .env file as follow (replace brackets with your own credentials) :
```
SMTP_HOST=<smtp-host.tld>:587
SMTP_USER=<user@host.tld>
SMTP_PASS=<password>
SMTP_FROM='"Corteza-CRM" <<user@host.tld>>'
```
4. Go to your Corteza instance (normally followed by _/auth_).
5. Create a new admin user. A confirmation email should be send by the server. We can see that the email notification is processed by checking the docker-compose logs : 
`server_1  | 17:44:02.160        DEBUG   service.auth-notification       sending auth notification       {"requestID": "<request_id>", "name": "auth_email_confirm", "email": "<my-mail@host.tld>"}`
6. An error is thrown (see the **Error message** section).

**Expected behavior**
The mail should be sent without error. Also, it should be received by the recipient, which is not the case.

**Error message**
> could not send email: gomail: could not send email 1: 554 5.2.252 SendAsDenied; <my-mail@host.tld> not allowed to send as info@example.tld;

**Additional context**
Same as #7 
I don't know if it could be linked, but I cannot create a healthy server container ; the server healthcheck is fine when checking _/healthcheck_, but the `docker-compose ps` command shows that the server is unhealthy. Few days ago, I tested Corteza without SMTP, and everything worked fine, even if the server container was unhealthy.

**Comment by darh** [comment]
Can you share the version you're using?

Does this help in any way:
https://docs.cortezaproject.org/corteza-docs/2021.9/administrator-guide/email-settings.html

**Comment by bio58** [comment]
Sure ! Here is the response : 

> {"response":{"buildTime":"2021-11-10T17:41:27Z","version":"2021.9.1"}}

Yep, I checked the page already but I can't even get to the admin setup page because the admin creation is blocked by the missing mail confirmation. Thanks :)

**Comment by darh** [comment]
Can you afford to drop the db and recreate the whole thing? That would be the easiest way.
Alternatively:
 - go to the db and inspect the settings table, look for rows with `auth.internal.....` keys; they are quite self explanatory
 - use the CLI and alter the settings
 - use the CLI and create the user and/or change the password

**Comment by bio58** [comment]
I tried to drop the DB and recreate the whole server/database folder after dropping the container multiples times with the same results. I will try to go to the DB to look it up tell you if it works.

**Comment by bio58** [comment]
Well, I tried to execute the following command : `corteza-server users add --help` (see the [documentation](https://docs.cortezaproject.org/corteza-docs/2021.9/devops-guide/maintenance/cli-reference.html)), but I got the following error :  

> corteza-server: command not found

How do I install the corteza package ? I used a docker container to install Corteza on my server, so I try : `docker exec corteza_db_1 corteza-server roles user add --help` but I get :

> OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "corteza-server": executable file not found in $PATH: unknown

Any idea of how to solve that problem ? Also, I will try to comment the SMTP_FROM field to see if it works.

**Comment by bio58** [comment]
Okay so if I do not specify a SMTP_FROM value, the server assign info@example.tld as value by default. Even when I drop the database, I can't change it via the .env file.

**Comment by bio58** [comment]
Here is something interesting : I drop the database and create a new container without SMTP and it seems that the SMTP options section in the settings is missing :
<img width="1438" alt="screenshot" src="https://user-images.githubusercontent.com/94072588/141316155-90c0b95d-6eff-4d5e-afa5-d5f800e471cf.png">

**Comment by darh** [comment]
Ok, thanks for pointing this out @bio58. will take a look and followup here.

**Comment by darh** [comment]
@bio58 could it be that you are looking at the wrong screen in the Admin panel?

![Screenshot 2022-01-04 at 08 34 12](https://user-images.githubusercontent.com/1500447/148024730-7405b612-648b-4dbe-85f1-188993625e9b.png)

**Comment by bio58** [comment]
Hi @darh 
Sorry but I uninstalled Corteza and switched to another software because at that time, I really needed to set it up quickly. However, from what I remembered, I did not have that section in the side panel, that's why I had to check in the **Settings** section.
If I got the time I will try to reinstall Corteza and will keep you informed.
