### ISSUE TITLE
Workflow Prompt

### ISSUE THREAD

**Issue by angielskim** [cortezaproject/corteza-server#298]
Trigger: Compose record: Before Create
Adding a prompt (non-blocking message to the user) does not block a record from being saved in case of an error.

Record saved (Wrong)
![prompt](https://user-images.githubusercontent.com/92810544/143572373-58ecd604-e1a8-478c-8456-40493f7d1a31.png)

Record not saved (OK)
![noprompt](https://user-images.githubusercontent.com/92810544/143572371-d49529f5-bb9b-47d7-ae79-2601b900380b.png)

**Comment by darh** [comment]
Hi @angielskim this is by design.

https://docs.cortezaproject.org/corteza-docs/2021.9/integrator-guide/automation/execution-flow-details.html#exec-flow-deferred

Current design does not allow interactive interruptions as one in your example.

**Comment by angielskim** [comment]
So how can I implement the following example?
Now no matter if the user exists or not the record is saved.
![obraz](https://user-images.githubusercontent.com/92810544/143578092-92776be5-ed17-4773-b5fd-f251a25a2d38.png)
If I remove the prompt everything is ok but I need a success message with some info.
