### ISSUE TITLE
Duplicate entry error when trying to save a record with a multiple select

### ISSUE THREAD

**Issue by lennyhorstink** [cortezaproject/corteza-server#30]
**Describe the bug**
I have a module with a record field that allows multiple select. I can select them, but when I save, I get: "Could not update this record: exec query failed. Error 1062. Duplicate entry '112231180576751620-MailingList-0' for key 'PRIMARY'"

**To Reproduce**
1. Go to https://latest.cortezaproject.org/compose/ns/service-cloud/pages/100056965736038402/record/112231180576751620/edit
2. In the "mailing list" field on the right, select multiple users
3. Hit save
-> the error "Could not update this record: exec query failed. Error 1062. Duplicate entry '112231180576751620-MailingList-0' for key 'PRIMARY'" shows

**Expected behavior**
I expect to be able to save multiple records.

**Screenshots**
![image](https://user-images.githubusercontent.com/34375645/66427004-6ae23a80-ea13-11e9-82e8-2b022359753b.png)

**Desktop (please complete the following information):**
- Firefox (latest)

**Additional context**
If I select only 1 record in the "mailing list" field, it saves without problem. This error only shows with 2 or more selected values.

**Comment by darh** [comment]
Deployed on latest.
