### ISSUE TITLE
Value validation - Field "Text displayed when expression is true" is diabled

### ISSUE THREAD

**Issue by angielskim** [cortezaproject/corteza-server#300]
**Describe the bug**
Value validation - Field "Text displayed when expression is true" is diabled

**To Reproduce**
Add Value validation

**Workaround**
Remove "disabled" flag in Developer Tools

**Version**
2021.9.4-rc.1

**Screenshots**
![field](https://user-images.githubusercontent.com/92810544/143861800-922e50da-cae4-48d3-b368-afccf15301ab.png)

**Comment by tjerman** [comment]
Thanks for reporting; we'll address it most likely in the next patch release.
This is an artefact from the early resource translation development days; I need to clarify a few bits before implementing a fix for it.
For now, please use the workaround

**Comment by darh** [comment]
Scheduled for 2021.9.6 patch release ( ~🎄  )

**Comment by darh** [comment]
This is now merged into `2021.9.x` branch.
