### ISSUE TITLE
Support for additional external record storage (ERS) connection adapter

### ISSUE THREAD

**Issue by zmija** [cortezaproject/corteza-server#71]
In addition to native connection (using existing connection to corteza db), add support for additional record storages. 

This adapter needs to support all CRUD & filtering operations to fetch & store records from and to external storage. 

Examples:

- use records tables inside primary database (current & default behaviour)
    - no extra configuration is needed
    - 2 tables are used record + record_values
- use a dedicated physical table to store records inside primary database
    - admin can set a dedicated db table
    - ??? how to solve multi-value fields
    - ??? should table exist or will we create it?
- interface to MongoDB
- interface to ElasticSearch
- interface to a specific endpoint on external REST API
- …

New ERS are enabled and configured through general admin interface.

All interaction with records should be then transparently handled by adapter.

Module configuration interface is extended - admin can then pick one of the adaptors and provide extra config if needed

**Comment by selcukbeyhan** [comment]
Hi, do you know if this is implemented or will be implemented?
