### ISSUE TITLE
Request Index abilities for columns

### ISSUE THREAD

**Issue by yangyi-bupt** [cortezaproject/corteza-server#80]
To accelerate the _search_, or to support the **unique** column feature, it's a request to build indexes on the _compose_record_values_. 

A possible solution may be to use the indexes pivot table like _force.com_.

https://developer.salesforce.com/page/Multi_Tenant_Architecture
http://www.developerforce.com/media/ForcedotcomBookLibrary/Force.com_Multitenancy_WP_101508.pdf

**Comment by darh** [comment]
Hi @yangyi-bupt 

Unique constraints are already in the develop branch
Other features that solve other problems you're describing will come soon too.

**Comment by darh** [comment]
I have to admit no progress was done on this. However, we are keeping it in an internal backlog.
