### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ErwinJunge** [cortezaproject/corteza-server#99]
**Is your feature request related to a problem? Please describe.**
I think this project would be a good fit for some people that I know, but sadly they're not fluent in English. 

**Describe the solution you'd like**
It would be great if this project supported translations, so that the community could then translate the software to their own languages.

**Describe alternatives you've considered**
I've looked through the docs and the code, but couldn't find support for translations. Without technical support, I can't think of an alternative.

**Comment by darh** [comment]
See #154, Closing, dup.
